const NIHONGO_DATA = {
    kana: {
        hiragana: [
            { jp: 'あ', en: 'a' }, { jp: 'い', en: 'i' }, { jp: 'う', en: 'u' }, { jp: 'え', en: 'e' }, { jp: 'お', en: 'o' },
            { jp: 'か', en: 'ka' }, { jp: 'き', en: 'ki' }, { jp: 'く', en: 'ku' }, { jp: 'け', en: 'ke' }, { jp: 'こ', en: 'ko' },
            { jp: 'さ', en: 'sa' }, { jp: 'し', en: 'shi' }, { jp: 'す', en: 'su' }, { jp: 'せ', en: 'se' }, { jp: 'そ', en: 'so' },
            { jp: 'た', en: 'ta' }, { jp: 'ち', en: 'chi' }, { jp: 'つ', en: 'tsu' }, { jp: 'て', en: 'te' }, { jp: 'と', en: 'to' },
            { jp: 'な', en: 'na' }, { jp: 'に', en: 'ni' }, { jp: 'ぬ', en: 'nu' }, { jp: 'ね', en: 'ne' }, { jp: 'の', en: 'no' },
            { jp: 'は', en: 'ha' }, { jp: 'ひ', en: 'hi' }, { jp: 'ふ', en: 'fu' }, { jp: 'へ', en: 'he' }, { jp: 'ほ', en: 'ho' },
            { jp: 'ま', en: 'ma' }, { jp: 'み', en: 'mi' }, { jp: 'む', en: 'mu' }, { jp: 'め', en: 'me' }, { jp: 'も', en: 'mo' },
            { jp: 'や', en: 'ya' }, { jp: 'ゆ', en: 'yu' }, { jp: 'よ', en: 'yo' },
            { jp: 'ら', en: 'ra' }, { jp: 'り', en: 'ri' }, { jp: 'る', en: 'ru' }, { jp: 'れ', en: 're' }, { jp: 'ろ', en: 'ro' },
            { jp: 'わ', en: 'wa' }, { jp: 'を', en: 'wo' }, { jp: 'ん', en: 'n' }
        ],
        katakana: [
            { jp: 'ア', en: 'a' }, { jp: 'イ', en: 'i' }, { jp: 'ウ', en: 'u' }, { jp: 'エ', en: 'e' }, { jp: 'オ', en: 'o' },
            { jp: 'カ', en: 'ka' }, { jp: 'キ', en: 'ki' }, { jp: 'ク', en: 'ku' }, { jp: 'ケ', en: 'ke' }, { jp: 'コ', en: 'ko' },
            { jp: 'サ', en: 'sa' }, { jp: 'シ', en: 'shi' }, { jp: 'ス', en: 'su' }, { jp: 'セ', en: 'se' }, { jp: 'ソ', en: 'so' },
            { jp: 'タ', en: 'ta' }, { jp: 'チ', en: 'chi' }, { jp: 'ツ', en: 'tsu' }, { jp: 'テ', en: 'te' }, { jp: 'ト', en: 'to' }
        ]
    },
    vocab: [
        // Nomina (Kata Benda)
        { jp: 'せんせい', romaji: 'Sensei', en: 'Guru', type: 'Meishi' },
        { jp: 'がくせい', romaji: 'Gakusei', en: 'Siswa', type: 'Meishi' },
        { jp: 'にほんご', romaji: 'Nihongo', en: 'Bahasa Jepang', type: 'Meishi' },
        { jp: 'ほん', romaji: 'Hon', en: 'Buku', type: 'Meishi' },
        { jp: 'くるま', romaji: 'Kuruma', en: 'Mobil', type: 'Meishi' },
        { jp: 'でんわ', romaji: 'Denwa', en: 'Telepon', type: 'Meishi' },
        { jp: 'たべもの', romaji: 'Tabemono', en: 'Makanan', type: 'Meishi' },
        { jp: 'のみもの', romaji: 'Nomimono', en: 'Minuman', type: 'Meishi' },
        { jp: 'かばん', romaji: 'Kaban', en: 'Tas', type: 'Meishi' },
        { jp: 'とけい', romaji: 'Tokei', en: 'Jam', type: 'Meishi' },
        { jp: 'みず', romaji: 'Mizu', en: 'Air', type: 'Meishi' },
        { jp: 'ごはん', romaji: 'Gohan', en: 'Nasi / Makan', type: 'Meishi' },
        { jp: 'いえ', romaji: 'Iie', en: 'Rumah', type: 'Meishi' },
        { jp: 'がっこう', romaji: 'Gakkou', en: 'Sekolah', type: 'Meishi' },
        { jp: 'てがみ', romaji: 'Tegami', en: 'Surat', type: 'Meishi' },
        { jp: 'しんぶん', romaji: 'Shinbun', en: 'Koran', type: 'Meishi' },
        { jp: 'ともだち', romaji: 'Tomodachi', en: 'Teman', type: 'Meishi' },
        { jp: 'かぞく', romaji: 'Kazoku', en: 'Keluarga', type: 'Meishi' },


        // Doushi (Kata Kerja)
        { jp: 'たべます', romaji: 'Tabemasu', en: 'Makan', type: 'Doushi' },
        { jp: 'のみます', romaji: 'Nomimasu', en: 'Minum', type: 'Doushi' },
        { jp: 'いきます', romaji: 'Ikimasu', en: 'Pergi', type: 'Doushi' },
        { jp: 'きます', romaji: 'Kimasu', en: 'Datang', type: 'Doushi' },
        { jp: 'かえります', romaji: 'Kaerimasu', en: 'Pulang', type: 'Doushi' },
        { jp: 'みます', romaji: 'Mimasu', en: 'Melihat', type: 'Doushi' },
        { jp: 'ききます', romaji: 'Kikimasu', en: 'Mendengar', type: 'Doushi' },
        { jp: 'よみます', romaji: 'Yomimasu', en: 'Membaca', type: 'Doushi' },
        { jp: 'かきます', romaji: 'Kakimasu', en: 'Menulis', type: 'Doushi' },
        { jp: 'べんきょうします', romaji: 'Benkyou shimasu', en: 'Belajar', type: 'Doushi' },
        { jp: 'ねます', romaji: 'Nemasu', en: 'Tidur', type: 'Doushi' },
        { jp: 'おきます', romaji: 'Okimasu', en: 'Bangun', type: 'Doushi' },
        { jp: 'はなします', romaji: 'Hanashimasu', en: 'Berbicara', type: 'Doushi' },
        { jp: 'あいます', romaji: 'Aimasu', en: 'Bertemu', type: 'Doushi' },
        { jp: 'わかります', romaji: 'Wakarimasu', en: 'Mengerti', type: 'Doushi' },
        { jp: 'しります', romaji: 'Shirimasu', en: 'Tahu', type: 'Doushi' },


        // I-keiyoushi (Kata Sifat-i)
        { jp: 'おいしい', romaji: 'Oishii', en: 'Enak', type: 'I-keiyoushi' },
        { jp: 'たかい', romaji: 'Takai', en: 'Mahal / Tinggi', type: 'I-keiyoushi' },
        { jp: 'やすい', romaji: 'Yasui', en: 'Murah', type: 'I-keiyoushi' },
        { jp: 'あつい', romaji: 'Atsui', en: 'Panas', type: 'I-keiyoushi' },
        { jp: 'さむい', romaji: 'Samui', en: 'Dingin (Cuaca)', type: 'I-keiyoushi' },
        { jp: 'おもしろい', romaji: 'Omoshiroi', en: 'Menarik / Lucu', type: 'I-keiyoushi' },
        { jp: 'ちいさい', romaji: 'Chiisai', en: 'Kecil', type: 'I-keiyoushi' },
        { jp: 'おおきい', romaji: 'Ookii', en: 'Besar', type: 'I-keiyoushi' },
        { jp: 'あたらしい', romaji: 'Atarashii', en: 'Baru', type: 'I-keiyoushi' },
        { jp: 'ふるい', romaji: 'Furui', en: 'Lama', type: 'I-keiyoushi' },
        { jp: 'たのしい', romaji: 'Tanoshii', en: 'Menyenangkan', type: 'I-keiyoushi' },
        { jp: 'いそがしい', romaji: 'Isogashii', en: 'Sibuk', type: 'I-keiyoushi' },
        { jp: 'わるい', romaji: 'Warui', en: 'Buruk', type: 'I-keiyoushi' },
        { jp: 'いい', romaji: 'Ii', en: 'Baik', type: 'I-keiyoushi' },
        { jp: 'おそい', romaji: 'Osoi', en: 'Lambat / Terlambat', type: 'I-keiyoushi' },
        { jp: 'はやい', romaji: 'Hayai', en: 'Cepat', type: 'I-keiyoushi' },


        // Na-keiyoushi (Kata Sifat-na)
        { jp: 'きれ', romaji: 'Kirei', en: 'Cantik / Bersih', type: 'Na-keiyoushi' },
        { jp: 'しずか', romaji: 'Shizuka', en: 'Tenang', type: 'Na-keiyoushi' },
        { jp: 'にぎやか', romaji: 'Nigiyaka', en: 'Ramai', type: 'Na-keiyoushi' },
        { jp: 'しんせつ', romaji: 'Shinsetsu', en: 'Baik Hati', type: 'Na-keiyoushi' },
        { jp: 'べんり', romaji: 'Benri', en: 'Praktis / Nyaman', type: 'Na-keiyoushi' },
        { jp: 'ゆうめい', romaji: 'Yuumei', en: 'Terkenal', type: 'Na-keiyoushi' },
        { jp: 'ひま', romaji: 'Hima', en: 'Senggang', type: 'Na-keiyoushi' },
        { jp: 'すき', romaji: 'Suki', en: 'Suka', type: 'Na-keiyoushi' },
        { jp: 'きらい', romaji: 'Kirai', en: 'Benci', type: 'Na-keiyoushi' },
        { jp: 'じょうず', romaji: 'Jouzu', en: 'Pandai', type: 'Na-keiyoushi' },
        { jp: 'へた', romaji: 'Heta', en: 'Tidak Pandai', type: 'Na-keiyoushi' },
        { jp: 'かんたん', romaji: 'Kantan', en: 'Mudah', type: 'Na-keiyoushi' },
        { jp: 'たいへん', romaji: 'Taihen', en: 'Berat / Sulit', type: 'Na-keiyoushi' },


        // Fukushi (Kata Keterangan)
        { jp: 'とても', romaji: 'Totemo', en: 'Sangat', type: 'Fukushi' },
        { jp: 'いつも', romaji: 'Itsumo', en: 'Selalu', type: 'Fukushi' },
        { jp: 'ときどき', romaji: 'Tokidoki', en: 'Kadang-kadang', type: 'Fukushi' },
        { jp: 'ゆっくり', romaji: 'Yukkuri', en: 'Perlahan', type: 'Fukushi' },
        { jp: 'すぐ', romaji: 'Sugu', en: 'Segera', type: 'Fukushi' },
        { jp: 'たくさん', romaji: 'Takusan', en: 'Banyak', type: 'Fukushi' },
        { jp: 'ちょっと', romaji: 'Chotto', en: 'Sedikit', type: 'Fukushi' },
        { jp: 'あまり', romaji: 'Amari', en: 'Tidak Begitu', type: 'Fukushi' },
        { jp: 'ぜんぜん', romaji: 'Zenzen', en: 'Sama Sekali Tidak', type: 'Fukushi' },

        // Additional Meishi (Kata Benda) - Daily Life
        { jp: 'あさごはん', romaji: 'Asagohan', en: 'Makan Pagi', type: 'Meishi' },
        { jp: 'ひるごはん', romaji: 'Hirugohan', en: 'Makan Siang', type: 'Meishi' },
        { jp: 'ばんごはん', romaji: 'Bangohan', en: 'Makan Malam', type: 'Meishi' },
        { jp: 'がっこう', romaji: 'Gakkou', en: 'Sekolah', type: 'Meishi' },
        { jp: 'かいしゃ', romaji: 'Kaisha', en: 'Perusahaan', type: 'Meishi' },
        { jp: 'びょういん', romaji: 'Byouin', en: 'Rumah Sakit', type: 'Meishi' },
        { jp: 'えき', romaji: 'Eki', en: 'Stasiun', type: 'Meishi' },
        { jp: 'くるま', romaji: 'Kuruma', en: 'Mobil', type: 'Meishi' },
        { jp: 'でんしゃ', romaji: 'Densha', en: 'Kereta', type: 'Meishi' },
        { jp: 'じてんしゃ', romaji: 'Jitensha', en: 'Sepeda', type: 'Meishi' },
        { jp: 'ほん', romaji: 'Hon', en: 'Buku', type: 'Meishi' },
        { jp: 'ノート', romaji: 'Nooto', en: 'Buku Catatan', type: 'Meishi' },
        { jp: 'えんぴつ', romaji: 'Enpitsu', en: 'Pensil', type: 'Meishi' },
        { jp: 'かばん', romaji: 'Kaban', en: 'Tas', type: 'Meishi' },
        { jp: 'とけい', romaji: 'Tokei', en: 'Jam', type: 'Meishi' },
        { jp: 'かさ', romaji: 'Kasa', en: 'Payung', type: 'Meishi' },
        { jp: 'くつ', romaji: 'Kutsu', en: 'Sepatu', type: 'Meishi' },
        { jp: 'さいふ', romaji: 'Saifu', en: 'Dompet', type: 'Meishi' },
        { jp: 'しんぶん', romaji: 'Shinbun', en: 'Koran', type: 'Meishi' },
        { jp: 'てがみ', romaji: 'Tegami', en: 'Surat', type: 'Meishi' },

        // Additional Doushi (Kata Kerja)
        { jp: 'かいます', romaji: 'Kaimasu', en: 'Membeli', type: 'Doushi' },
        { jp: 'ききます', romaji: 'Kikimasu', en: 'Mendengar', type: 'Doushi' },
        { jp: 'かきます', romaji: 'Kakimasu', en: 'Menulis', type: 'Doushi' },
        { jp: 'よみます', romaji: 'Yomimasu', en: 'Membaca', type: 'Doushi' },
        { jp: 'まちます', romaji: 'Machimasu', en: 'Menunggu', type: 'Doushi' },
        { jp: 'わかります', romaji: 'Wakarimasu', en: 'Mengerti', type: 'Doushi' },
        { jp: 'あそびます', romaji: 'Asobimasu', en: 'Bermain', type: 'Doushi' },
        { jp: 'およぎます', romaji: 'Oyogimasu', en: 'Berenang', type: 'Doushi' },
        { jp: 'あいます', romaji: 'Aimasu', en: 'Bertemu', type: 'Doushi' },
        { jp: 'はなします', romaji: 'Hanashimasu', en: 'Berbicara', type: 'Doushi' },

        // Additional Keiyoushi (Kata Sifat) & Others
        { jp: 'あまい', romaji: 'Amai', en: 'Manis', type: 'I-keiyoushi' },
        { jp: 'からい', romaji: 'Karai', en: 'Pedas', type: 'I-keiyoushi' },
        { jp: 'おもい', romaji: 'Omoi', en: 'Berat', type: 'I-keiyoushi' },
        { jp: 'かるい', romaji: 'Karui', en: 'Ringan', type: 'I-keiyoushi' },
        { jp: 'ひろい', romaji: 'Hiroi', en: 'Luas', type: 'I-keiyoushi' },
        { jp: 'せまい', romaji: 'Semai', en: 'Sempit', type: 'I-keiyoushi' },
        { jp: 'とおい', romaji: 'Tooi', en: 'Jauh', type: 'I-keiyoushi' },
        { jp: 'ちかい', romaji: 'Chikai', en: 'Dekat', type: 'I-keiyoushi' },
        { jp: 'たいせつ', romaji: 'Taisetsu', en: 'Penting', type: 'Na-keiyoushi' },
        { jp: 'あんぜん', romaji: 'Anzen', en: 'Aman', type: 'Na-keiyoushi' },

        // Colors & Time
        { jp: 'あか', romaji: 'Aka', en: 'Merah', type: 'Meishi' },
        { jp: 'あお', romaji: 'Ao', en: 'Biru', type: 'Meishi' },
        { jp: 'しろ', romaji: 'Shiro', en: 'Putih', type: 'Meishi' },
        { jp: 'くろ', romaji: 'Kuro', en: 'Hitam', type: 'Meishi' },
        { jp: 'きょう', romaji: 'Kyou', en: 'Hari Ini', type: 'Meishi' },
        { jp: 'あした', romaji: 'Ashita', en: 'Besok', type: 'Meishi' },
        { jp: 'きのう', romaji: 'Kinou', en: 'Kemarin', type: 'Meishi' },
        { jp: 'らいしゅう', romaji: 'Raishu', en: 'Minggu Depan', type: 'Meishi' },
        { jp: 'こんしゅう', romaji: 'Konshuu', en: 'Minggu Ini', type: 'Meishi' },
        { jp: 'せんしゅう', romaji: 'Senshuu', en: 'Minggu Lalu', type: 'Meishi' },


        // Family (Kazoku)
        { jp: 'かぞく', romaji: 'Kazoku', en: 'Keluarga', type: 'Meishi' },
        { jp: 'ちち', romaji: 'Chichi', en: 'Ayah (Sendiri)', type: 'Meishi' },
        { jp: 'はは', romaji: 'Haha', en: 'Ibu (Sendiri)', type: 'Meishi' },
        { jp: 'おとうさん', romaji: 'Otousan', en: 'Ayah (Orang lain)', type: 'Meishi' },
        { jp: 'おかあさん', romaji: 'Okaasan', en: 'Ibu (Orang lain)', type: 'Meishi' },
        { jp: 'あに', romaji: 'Ani', en: 'Kakak Laki-laki (Sendiri)', type: 'Meishi' },
        { jp: 'あね', romaji: 'Ane', en: 'Kakak Perempuan (Sendiri)', type: 'Meishi' },
        { jp: 'おとうと', romaji: 'Otouto', en: 'Adik Laki-laki', type: 'Meishi' },
        { jp: 'いもうと', romaji: 'Imouto', en: 'Adik Perempuan', type: 'Meishi' },
        { jp: 'きょうだい', romaji: 'Kyoudai', en: 'Saudara', type: 'Meishi' },

        // Body Parts (Karada)
        { jp: 'からだ', romaji: 'Karada', en: 'Tubuh', type: 'Meishi' },
        { jp: 'あたま', romaji: 'Atama', en: 'Kepala', type: 'Meishi' },
        { jp: 'め', romaji: 'Me', en: 'Mata', type: 'Meishi' },
        { jp: 'みみ', romaji: 'Mimi', en: 'Telinga', type: 'Meishi' },
        { jp: 'くち', romaji: 'Kuchi', en: 'Mulut', type: 'Meishi' },
        { jp: 'は', romaji: 'Ha', en: 'Gigi', type: 'Meishi' },
        { jp: 'て', romaji: 'Te', en: 'Tangan', type: 'Meishi' },
        { jp: 'あし', romaji: 'Ashi', en: 'Kaki', type: 'Meishi' },
        { jp: 'おなか', romaji: 'Onaka', en: 'Perut', type: 'Meishi' },
        { jp: 'かみ', romaji: 'Kami', en: 'Rambut', type: 'Meishi' },

        // Animals (Doubutsu)
        { jp: 'いぬ', romaji: 'Inu', en: 'Anjing', type: 'Meishi' },
        { jp: 'ねこ', romaji: 'Neko', en: 'Kucing', type: 'Meishi' },
        { jp: 'とり', romaji: 'Tori', en: 'Burung', type: 'Meishi' },
        { jp: 'さかな', romaji: 'Sakana', en: 'Ikan', type: 'Meishi' },
        { jp: 'うし', romaji: 'Ushi', en: 'Sapi', type: 'Meishi' },
        { jp: 'うま', romaji: 'Uma', en: 'Kuda', type: 'Meishi' },
        { jp: 'ぶた', romaji: 'Buta', en: 'Babi', type: 'Meishi' },
        { jp: 'さる', romaji: 'Saru', en: 'Monyet', type: 'Meishi' },
        { jp: 'ぞう', romaji: 'Zou', en: 'Gajah', type: 'Meishi' },
        { jp: 'ライオン', romaji: 'Raion', en: 'Singa', type: 'Meishi' },

        // Food & Drink (Tabemono & Nomimono)
        { jp: 'ごはん', romaji: 'Gohan', en: 'Nasi', type: 'Meishi' },
        { jp: 'パン', romaji: 'Pan', en: 'Roti', type: 'Meishi' },
        { jp: 'たまご', romaji: 'Tamago', en: 'Telur', type: 'Meishi' },
        { jp: 'にく', romaji: 'Niku', en: 'Daging', type: 'Meishi' },
        { jp: 'やさい', romaji: 'Yasai', en: 'Sayuran', type: 'Meishi' },
        { jp: 'くだもの', romaji: 'Kudamono', en: 'Buah-buahan', type: 'Meishi' },
        { jp: 'みず', romaji: 'Mizu', en: 'Air', type: 'Meishi' },
        { jp: 'おちゃ', romaji: 'Ocha', en: 'Teh', type: 'Meishi' },
        { jp: 'コーヒー', romaji: 'Koohii', en: 'Kopi', type: 'Meishi' },
        { jp: 'ぎゅうにゅう', romaji: 'Gyuunyuu', en: 'Susu Sapi', type: 'Meishi' },

        // Places (Basho)
        { jp: 'としょかん', romaji: 'Toshokan', en: 'Perpustakaan', type: 'Meishi' },
        { jp: 'ゆうびんきょく', romaji: 'Yuubinkyoku', en: 'Kantor Pos', type: 'Meishi' },
        { jp: 'ぎんこう', romaji: 'Ginkou', en: 'Bank', type: 'Meishi' },
        { jp: 'こうえん', romaji: 'Kouen', en: 'Taman', type: 'Meishi' },
        { jp: 'きっさてん', romaji: 'Kissaten', en: 'Kafe', type: 'Meishi' },
        { jp: 'スーパー', romaji: 'Suupaa', en: 'Supermarket', type: 'Meishi' },
        { jp: 'デパート', romaji: 'Depaato', en: 'Departemen Store', type: 'Meishi' },
        { jp: 'トイレ', romaji: 'Toire', en: 'Toilet', type: 'Meishi' },
        { jp: 'みせ', romaji: 'Mise', en: 'Toko', type: 'Meishi' },
        { jp: 'うけつけ', romaji: 'Uketsuke', en: 'Resepsionis', type: 'Meishi' },

        // Daily Actions (More Verbs)
        { jp: 'ねます', romaji: 'Nemasu', en: 'Tidur', type: 'Doushi' },
        { jp: 'おきます', romaji: 'Okimasu', en: 'Bangun', type: 'Doushi' },
        { jp: 'はたらきます', romaji: 'Hatarakimasu', en: 'Bekerja', type: 'Doushi' },
        { jp: 'やすみます', romaji: 'Yasumimasu', en: 'Beristirahat', type: 'Doushi' },
        { jp: 'べんきょうします', romaji: 'Benkyoushimasu', en: 'Belajar', type: 'Doushi' },
        { jp: 'かえります', romaji: 'Kaerimasu', en: 'Pulang', type: 'Doushi' },
        { jp: 'いきます', romaji: 'Ikimasu', en: 'Pergi', type: 'Doushi' },
        { jp: 'きます', romaji: 'Kimasu', en: 'Datang', type: 'Doushi' },
        { jp: 'たべます', romaji: 'Tabemasu', en: 'Makan', type: 'Doushi' },
        { jp: 'のみます', romaji: 'Nomimasu', en: 'Minum', type: 'Doushi' },

        // Hobbies & Entertainment
        { jp: 'えいが', romaji: 'Eiga', en: 'Film', type: 'Meishi' },
        { jp: 'おんがく', romaji: 'Ongaku', en: 'Musik', type: 'Meishi' },
        { jp: 'うた', romaji: 'Uta', en: 'Lagu', type: 'Meishi' },
        { jp: 'え', romaji: 'E', en: 'Gambar / Lukisan', type: 'Meishi' },
        { jp: 'しゃしん', romaji: 'Shashin', en: 'Foto', type: 'Meishi' },
        { jp: 'スポーツ', romaji: 'Supootsu', en: 'Olahraga', type: 'Meishi' },
        { jp: 'りょこう', romaji: 'Ryokou', en: 'Traveling', type: 'Meishi' },
        { jp: 'どくしょ', romaji: 'Dokusho', en: 'Membaca Buku', type: 'Meishi' },
        { jp: 'ゲーム', romaji: 'Geemu', en: 'Game', type: 'Meishi' },
        { jp: 'カラオケ', romaji: 'Karaoke', en: 'Karaoke', type: 'Meishi' },

        // Transportation (Norimono)
        { jp: 'ひこうき', romaji: 'Hikouki', en: 'Pesawat', type: 'Meishi' },
        { jp: 'ふね', romaji: 'Fune', en: 'Kapal', type: 'Meishi' },
        { jp: 'ちかてつ', romaji: 'Chikatetsu', en: 'Kereta Bawah Tanah', type: 'Meishi' },
        { jp: 'タクシー', romaji: 'Takushii', en: 'Taksi', type: 'Meishi' },
        { jp: 'バス', romaji: 'Basu', en: 'Bus', type: 'Meishi' },
        { jp: 'しんかんせん', romaji: 'Shinkansen', en: 'Kereta Cepat', type: 'Meishi' },
        { jp: 'オートバイ', romaji: 'Ootobai', en: 'Motor', type: 'Meishi' },
        { jp: 'あるいて', romaji: 'Aruite', en: 'Jalan kaki', type: 'Meishi' },

        // Time Expressions (Jikan)
        { jp: 'あき', romaji: 'Aki', en: 'Musim Gugur', type: 'Meishi' },
        { jp: 'ふゆ', romaji: 'Fuyu', en: 'Musim Dingin', type: 'Meishi' },
        { jp: 'はる', romaji: 'Haru', en: 'Musim Semi', type: 'Meishi' },
        { jp: 'なつ', romaji: 'Natsu', en: 'Musim Panas', type: 'Meishi' },
        { jp: 'あさ', romaji: 'Asa', en: 'Pagi', type: 'Meishi' },
        { jp: 'ひる', romaji: 'Hiru', en: 'Siang', type: 'Meishi' },
        { jp: 'ばん', romaji: 'Ban', en: 'Malam', type: 'Meishi' },
        { jp: 'よる', romaji: 'Yoru', en: 'Malam (Larut)', type: 'Meishi' },
        { jp: 'いま', romaji: 'Ima', en: 'Sekarang', type: 'Meishi' },
        { jp: 'まいにち', romaji: 'Mainichi', en: 'Setiap Hari', type: 'Meishi' },

        // Occupations (Shokugyou)
        { jp: 'せんせい', romaji: 'Sensei', en: 'Guru / Dokter', type: 'Meishi' },
        { jp: 'がくせい', romaji: 'Gakusei', en: 'Siswa', type: 'Meishi' },
        { jp: 'かいしゃいん', romaji: 'Kaishain', en: 'Karyawan', type: 'Meishi' },
        { jp: 'ぎんこういん', romaji: 'Ginkouin', en: 'Pegawai Bank', type: 'Meishi' },
        { jp: 'いしゃ', romaji: 'Isha', en: 'Dokter', type: 'Meishi' },
        { jp: 'けんきゅうしゃ', romaji: 'Kenkyuusha', en: 'Peneliti', type: 'Meishi' },
        { jp: 'エンジニア', romaji: 'Enjinia', en: 'Insinyur', type: 'Meishi' },
        { jp: 'だいがく', romaji: 'Daigaku', en: 'Universitas', type: 'Meishi' },
        { jp: 'きょうし', romaji: 'Kyoushi', en: 'Guru (Profesi)', type: 'Meishi' },

        // House Objects (Ie no mono)
        { jp: 'ベッド', romaji: 'Beddo', en: 'Tempat Tidur', type: 'Meishi' },
        { jp: 'エアコン', romaji: 'Eakon', en: 'AC', type: 'Meishi' },
        { jp: 'スイッチ', romaji: 'Suicchi', en: 'Sakelar', type: 'Meishi' },
        { jp: 'テーブル', romaji: 'Teeburu', en: 'Meja Makan', type: 'Meishi' },
        { jp: 'ソファー', romaji: 'Sofaa', en: 'Sofa', type: 'Meishi' },
        { jp: 'カレンダー', romaji: 'Karendaa', en: 'Kalender', type: 'Meishi' },
        { jp: 'ゴミばこ', romaji: 'Gomibako', en: 'Tempat Sampah', type: 'Meishi' },
        { jp: 'はこ', romaji: 'Hako', en: 'Kotak', type: 'Meishi' },

        // Fruits (Kudamono)
        { jp: 'りんご', romaji: 'Ringo', en: 'Apel', type: 'Meishi' },
        { jp: 'みかん', romaji: 'Mikan', en: 'Jeruk Mandarin', type: 'Meishi' },
        { jp: 'バナナ', romaji: 'Banana', en: 'Pisang', type: 'Meishi' },
        { jp: 'ぶどう', romaji: 'Budou', en: 'Anggur', type: 'Meishi' },
        { jp: 'すいか', romaji: 'Suika', en: 'Semangka', type: 'Meishi' },
        { jp: 'いちご', romaji: 'Ichigo', en: 'Stroberi', type: 'Meishi' },
        { jp: 'メロン', romaji: 'Meron', en: 'Melon', type: 'Meishi' },
        { jp: 'パイナップル', romaji: 'Painappuru', en: 'Nanas', type: 'Meishi' },
        { jp: 'レモン', romaji: 'Remon', en: 'Lemon', type: 'Meishi' },
        { jp: 'モモ', romaji: 'Momo', en: 'Persik', type: 'Meishi' },

        // Vegetables (Yasai)
        { jp: 'トマト', romaji: 'Tomato', en: 'Tomat', type: 'Meishi' },
        { jp: 'にんじん', romaji: 'Ninjin', en: 'Wortel', type: 'Meishi' },
        { jp: 'じゃがいも', romaji: 'Jagaimo', en: 'Kentang', type: 'Meishi' },
        { jp: 'たまねぎ', romaji: 'Tamanegi', en: 'Bawang Bombay', type: 'Meishi' },
        { jp: 'きゅうり', romaji: 'Kyuuri', en: 'Timun', type: 'Meishi' },
        { jp: 'なす', romaji: 'Nasu', en: 'Terong', type: 'Meishi' },
        { jp: 'キャベツ', romaji: 'Kyabetsu', en: 'Kubis', type: 'Meishi' },
        { jp: 'レタス', romaji: 'Retasu', en: 'Selada', type: 'Meishi' },
        { jp: 'だいこん', romaji: 'Daikon', en: 'Lobak', type: 'Meishi' },
        { jp: 'とうもろこし', romaji: 'Toumorokoshi', en: 'Jagung', type: 'Meishi' },

        // School & Office (Gakkou & Kaisha)
        { jp: 'きょうしつ', romaji: 'Kyoushitsu', en: 'Kelas', type: 'Meishi' },
        { jp: 'じむしょ', romaji: 'Jimusho', en: 'Kantor (Ruangan)', type: 'Meishi' },
        { jp: 'かいぎしつ', romaji: 'Kaigishitsu', en: 'Ruang Rapat', type: 'Meishi' },
        { jp: 'しょくどう', romaji: 'Shokudou', en: 'Kantin', type: 'Meishi' },
        { jp: 'コンピューター', romaji: 'Konpyuutaa', en: 'Komputer', type: 'Meishi' },
        { jp: 'はさみ', romaji: 'Hasami', en: 'Gunting', type: 'Meishi' },
        { jp: 'ホッチキス', romaji: 'Hocchikisu', en: 'Stapler', type: 'Meishi' },
        { jp: 'けしゴム', romaji: 'Keshigomu', en: 'Penghapus', type: 'Meishi' },
        { jp: 'ボールペン', romaji: 'Boorupen', en: 'Bolpoin', type: 'Meishi' },
        { jp: 'じしょ', romaji: 'Jisho', en: 'Kamus', type: 'Meishi' },

        // City Infrastructure (Machi)
        { jp: 'まち', romaji: 'Machi', en: 'Kota', type: 'Meishi' },
        { jp: 'みち', romaji: 'Michi', en: 'Jalan', type: 'Meishi' },
        { jp: 'こうばん', romaji: 'Kouban', en: 'Pos Polisi', type: 'Meishi' },
        { jp: 'たてもの', romaji: 'Tatemono', en: 'Bangunan', type: 'Meishi' },
        { jp: 'びじゅつかん', romaji: 'Bijutsukan', en: 'Museum Seni', type: 'Meishi' },
        { jp: 'はくぶつかん', romaji: 'Hakubutsukan', en: 'Museum', type: 'Meishi' },
        { jp: 'コンビニ', romaji: 'Konbini', en: 'Minimarket', type: 'Meishi' },
        { jp: 'スーパー', romaji: 'Suupaa', en: 'Supermarket', type: 'Meishi' },
        { jp: 'ホテル', romaji: 'Hoteru', en: 'Hotel', type: 'Meishi' },
        { jp: 'たいしかん', romaji: 'Taishikan', en: 'Kedutaan', type: 'Meishi' },

        // Abstract Nouns & Concepts
        { jp: 'ゆめ', romaji: 'Yume', en: 'Mimpi', type: 'Meishi' },
        { jp: 'きもち', romaji: 'Kimochi', en: 'Perasaan', type: 'Meishi' },
        { jp: 'かんじ', romaji: 'Kanji', en: 'Huruf Kanji / Rasa', type: 'Meishi' },
        { jp: 'しごと', romaji: 'Shigoto', en: 'Pekerjaan', type: 'Meishi' },
        { jp: 'じゅぎょう', romaji: 'Jugyou', en: 'Pelajaran', type: 'Meishi' },
        { jp: 'しゅくだい', romaji: 'Shukudai', en: 'PR', type: 'Meishi' },
        { jp: 'しけん', romaji: 'Shiken', en: 'Ujian', type: 'Meishi' },
        { jp: 'やくそく', romaji: 'Yakusoku', en: 'Janji', type: 'Meishi' },
        { jp: 'ようじ', romaji: 'Youji', en: 'Urusan', type: 'Meishi' },
        { jp: 'おかね', romaji: 'Okane', en: 'Uang', type: 'Meishi' },

        // Nature & Weather
        { jp: 'そら', romaji: 'Sora', en: 'Langit', type: 'Meishi' },
        { jp: 'うみ', romaji: 'Umi', en: 'Laut', type: 'Meishi' },
        { jp: 'やま', romaji: 'Yama', en: 'Gunung', type: 'Meishi' },
        { jp: 'かわ', romaji: 'Kawa', en: 'Sungai', type: 'Meishi' },
        { jp: 'はな', romaji: 'Hana', en: 'Bunga', type: 'Meishi' },
        { jp: 'き', romaji: 'Ki', en: 'Pohon', type: 'Meishi' },
        { jp: 'あめ', romaji: 'Ame', en: 'Hujan / Permen', type: 'Meishi' },
        { jp: 'ゆき', romaji: 'Yuki', en: 'Salju', type: 'Meishi' },
        { jp: 'はれ', romaji: 'Hare', en: 'Cerah', type: 'Meishi' },
        { jp: 'くもり', romaji: 'Kumori', en: 'Berawan', type: 'Meishi' },

        // Clothing & Accessories
        { jp: 'ふく', romaji: 'Fuku', en: 'Baju', type: 'Meishi' },
        { jp: 'シャツ', romaji: 'Shatsu', en: 'Kemeja', type: 'Meishi' },
        { jp: 'ズボン', romaji: 'Zubon', en: 'Celana', type: 'Meishi' },
        { jp: 'スカート', romaji: 'Sukaato', en: 'Rok', type: 'Meishi' },
        { jp: 'ぼうし', romaji: 'Boushi', en: 'Topi', type: 'Meishi' },
        { jp: 'メガネ', romaji: 'Megane', en: 'Kacamata', type: 'Meishi' },
        { jp: 'きます', romaji: 'Kimasu', en: 'Memakai (Baju)', type: 'Doushi' },
        { jp: 'はきます', romaji: 'Hakimasu', en: 'Memakai (Celana/Sepatu)', type: 'Doushi' },
        { jp: 'ぬぎます', romaji: 'Nugimasu', en: 'Melepas (Pakaian)', type: 'Doushi' },
        { jp: 'あらいます', romaji: 'Araimasu', en: 'Mencuci', type: 'Doushi' },

        // Directions & Positions
        { jp: 'うえ', romaji: 'Ue', en: 'Atas', type: 'Meishi' },
        { jp: 'した', romaji: 'Shita', en: 'Bawah', type: 'Meishi' },
        { jp: 'まえ', romaji: 'Mae', en: 'Depan', type: 'Meishi' },
        { jp: 'うしろ', romaji: 'Ushiro', en: 'Belakang', type: 'Meishi' },
        { jp: 'みぎ', romaji: 'Migi', en: 'Kanan', type: 'Meishi' },
        { jp: 'ひだり', romaji: 'Hidari', en: 'Kiri', type: 'Meishi' },
        { jp: 'なか', romaji: 'Naka', en: 'Dalam', type: 'Meishi' },
        { jp: 'そと', romaji: 'Soto', en: 'Luar', type: 'Meishi' },
        { jp: 'となり', romaji: 'Tonari', en: 'Sebelah', type: 'Meishi' },
        { jp: 'ちかく', romaji: 'Chikaku', en: 'Dekat (Lokasi)', type: 'Meishi' },

        // Household & Others
        { jp: 'いえ', romaji: 'Ie', en: 'Rumah', type: 'Meishi' },
        { jp: 'へや', romaji: 'Heya', en: 'Kamar', type: 'Meishi' },
        { jp: 'ドア', romaji: 'Doa', en: 'Pintu', type: 'Meishi' },
        { jp: 'まど', romaji: 'Mado', en: 'Jendela', type: 'Meishi' },
        { jp: 'つくえ', romaji: 'Tsukue', en: 'Meja Tulis', type: 'Meishi' },
        { jp: 'いす', romaji: 'Isu', en: 'Kursi', type: 'Meishi' },
        { jp: 'でんき', romaji: 'Denki', en: 'Listrik / Lampu', type: 'Meishi' },
        { jp: 'テレビ', romaji: 'Terebi', en: 'Televisi', type: 'Meishi' },
        { jp: 'れいぞうこ', romaji: 'Reizouko', en: 'Kulkas', type: 'Meishi' },
        { jp: 'かぎ', romaji: 'Kagi', en: 'Kunci', type: 'Meishi' },


        // Setsuzokushi (Kata Hubung)
        { jp: 'そして', romaji: 'Soshite', en: 'Dan (Kemudian)', type: 'Setsuzokushi' },
        { jp: 'それから', romaji: 'Sorekara', en: 'Setelah itu', type: 'Setsuzokushi' },
        { jp: 'でも', romaji: 'Demo', en: 'Tetapi', type: 'Setsuzokushi' },
        { jp: 'だから', romaji: 'Dakara', en: 'Oleh karena itu', type: 'Setsuzokushi' },

        // Joshi (Partikel)
        { jp: 'は', romaji: 'wa', en: 'Partikel Subjek', type: 'Joshi' },
        { jp: 'を', romaji: 'wo', en: 'Partikel Objek', type: 'Joshi' },
        { jp: 'に', romaji: 'ni', en: 'Partikel Tujuan/Waktu', type: 'Joshi' },
        { jp: 'へ', romaji: 'he', en: 'Partikel Arah', type: 'Joshi' },
        { jp: 'と', romaji: 'to', en: 'Partikel Dan/Bersama', type: 'Joshi' },
        { jp: 'も', romaji: 'mo', en: 'Partikel "Juga"', type: 'Joshi' }
    ],
    grammar: [
        {
            title: 'Watashi wa ... desu',
            desc: 'Digunakan untuk memperkenalkan diri atau menyatakan status.',
            example: 'わたしは だくせいです (Watashi wa gakusei desu) - Saya adalah seorang siswa.'
        }
    ],
    kanji: [
        // N5 - Dasar (100 Kanji)
        { char: '日', kun: 'hi', on: 'ニチ (NICHI)', mean: 'Hari / Matahari', level: 'N5' },
        { char: '月', kun: 'tsuki', on: 'ゲツ (GETSU)', mean: 'Bulan', level: 'N5' },
        { char: '火', kun: 'hi', on: 'カ (KA)', mean: 'Api', level: 'N5' },
        { char: '水', kun: 'mizu', on: 'スイ (SUI)', mean: 'Air', level: 'N5' },
        { char: '木', kun: 'ki', on: 'モク (MOKU)', mean: 'Pohon', level: 'N5' },
        { char: '金', kun: 'kane', on: 'キン (KIN)', mean: 'Emas / Uang', level: 'N5' },
        { char: '土', kun: 'tsuchi', on: 'ド (DO)', mean: 'Tanah', level: 'N5' },
        { char: '山', kun: 'yama', on: 'サン (SAN)', mean: 'Gunung', level: 'N5' },
        { char: '川', kun: 'kawa', on: 'セン (SEN)', mean: 'Sungai', level: 'N5' },
        { char: '田', kun: 'ta', on: 'デン (DEN)', mean: 'Sawah', level: 'N5' },
        { char: '人', kun: 'hito', on: 'ジン (JIN)', mean: 'Orang', level: 'N5' },
        { char: '子', kun: 'ko', on: 'シ (SHI)', mean: 'Anak', level: 'N5' },
        { char: '女', kun: 'onna', on: 'ジョ (JO)', mean: 'Perempuan', level: 'N5' },
        { char: '男', kun: 'otoko', on: 'ダン (DAN)', mean: 'Laki-laki', level: 'N5' },
        { char: '学', kun: 'mana', on: 'ガク (GAKU)', mean: 'Belajar', level: 'N5' },
        { char: '生', kun: 'i', on: 'セイ (SEI)', mean: 'Hidup / Lahir', level: 'N5' },
        { char: '先', kun: 'saki', on: 'セン (SEN)', mean: 'Sebelum', level: 'N5' },
        { char: '本', kun: 'moto', on: 'ホン (HON)', mean: 'Buku / Asal', level: 'N5' },
        { char: '年', kun: 'toshi', on: 'ネン (NEN)', mean: 'Tahun', level: 'N5' },
        { char: '何', kun: 'nani', on: 'カ (KA)', mean: 'Apa', level: 'N5' },
        { char: '一', kun: 'hito', on: 'イチ (ICHI)', mean: 'Satu', level: 'N5' },
        { char: '二', kun: 'futa', on: 'ニ (NI)', mean: 'Dua', level: 'N5' },
        { char: '三', kun: 'mi', on: 'サン (SAN)', mean: 'Tiga', level: 'N5' },
        { char: '四', kun: 'yo', on: 'シ (SHI)', mean: 'Empat', level: 'N5' },
        { char: '五', kun: 'itsu', on: 'ゴ (GO)', mean: 'Lima', level: 'N5' },
        { char: '六', kun: 'mu', on: 'ロク (ROKU)', mean: 'Enam', level: 'N5' },
        { char: '七', kun: 'nana', on: 'シチ (SHICHI)', mean: 'Tujuh', level: 'N5' },
        { char: '八', kun: 'ya', on: 'ハチ (HACHI)', mean: 'Delapan', level: 'N5' },
        { char: '九', kun: 'kokono', on: 'キュウ (KYUU)', mean: 'Sembilan', level: 'N5' },
        { char: '十', kun: 'too', on: 'ジュウ (JUU)', mean: 'Sepuluh', level: 'N5' },
        { char: '百', kun: '-', on: 'ヒャク (HYAKU)', mean: 'Seratus', level: 'N5' },
        { char: '千', kun: 'chi', on: 'セン (SEN)', mean: 'Seribu', level: 'N5' },
        { char: '万', kun: '-', on: 'マン (MAN)', mean: 'Sepuluh Ribu', level: 'N5' },
        { char: '大', kun: 'oo', on: 'ダイ (DAI)', mean: 'Besar', level: 'N5' },
        { char: '小', kun: 'ko', on: 'ショウ (SHOU)', mean: 'Kecil', level: 'N5' },
        { char: '中', kun: 'naka', on: 'チュウ (CHUU)', mean: 'Tengah / Dalam', level: 'N5' },
        { char: '国', kun: 'kuni', on: 'コク (KOKU)', mean: 'Negara', level: 'N5' },
        { char: '円', kun: 'まる', on: 'エン (EN)', mean: 'Yen / Lingkaran', level: 'N5' },
        { char: '時', kun: 'toki', on: 'ジ (JI)', mean: 'Waktu / Jam', level: 'N5' },
        { char: '間', kun: 'aida', on: 'カン (KAN)', mean: 'Interval / Antara', level: 'N5' },
        { char: '上', kun: 'ue', on: 'ジョウ (JOU)', mean: 'Atas', level: 'N5' },
        { char: '下', kun: 'shita', on: 'カ (KA)', mean: 'Bawah', level: 'N5' },
        { char: '左', kun: 'hidari', on: 'サ (SA)', mean: 'Kiri', level: 'N5' },
        { char: '右', kun: 'migi', on: 'ウ (U)', mean: 'Kanan', level: 'N5' },
        { char: '口', kun: 'kuchi', on: 'コウ (KOU)', mean: 'Mulut', level: 'N5' },
        { char: '耳', kun: 'mimi', on: 'ジ (JI)', mean: 'Telinga', level: 'N5' },
        { char: '目', kun: 'me', on: 'モク (MOKU)', mean: 'Mata', level: 'N5' },
        { char: '手', kun: 'te', on: 'シュ (SHU)', mean: 'Tangan', level: 'N5' },
        { char: '足', kun: 'ashi', on: 'ソク (SOKU)', mean: 'Kaki', level: 'N5' },
        { char: '見', kun: 'mi', on: 'ケン (KEN)', mean: 'Melihat', level: 'N5' },
        { char: '行', kun: 'i', on: 'コウ (KOU)', mean: 'Pergi', level: 'N5' },
        { char: '来', kun: 'ku', on: 'ライ (RAI)', mean: 'Datang', level: 'N5' },
        { char: '出', kun: 'de', on: 'シュツ (SHUTSU)', mean: 'Keluar', level: 'N5' },
        { char: '入', kun: 'hai / i', on: 'ニュウ (NYUU)', mean: 'Masuk', level: 'N5' },
        { char: '食', kun: 'ta', on: 'ショク (SHOKU)', mean: 'Makan', level: 'N5' },
        { char: '飲', kun: 'no', on: 'イン (IN)', mean: 'Minum', level: 'N5' },
        { char: '言', kun: 'i / koto', on: 'ゲン (GEN)', mean: 'Bicara / Kata', level: 'N5' },
        { char: '話', kun: 'hana', on: 'ワ (WA)', mean: 'Percakapan', level: 'N5' },
        { char: '語', kun: 'kata', on: 'ゴ (GO)', mean: 'Bahasa / Kata', level: 'N5' },
        { char: '読', kun: 'yo', on: 'ドク (DOKU)', mean: 'Membaca', level: 'N5' },
        { char: '書', kun: 'ka', on: 'ショ (SHO)', mean: 'Menulis', level: 'N5' },
        { char: '校', kun: '-', on: 'コウ (KOU)', mean: 'Sekolah', level: 'N5' },
        { char: '友', kun: 'tomo', on: 'ユウ (YUU)', mean: 'Teman', level: 'N5' },
        { char: '名', kun: 'na', on: 'メイ (MEI)', mean: 'Nama', level: 'N5' },
        { char: '前', kun: 'mae', on: 'ゼン (ZEN)', mean: 'Depan / Sebelum', level: 'N5' },
        { char: '後', kun: 'ato / ushi', on: 'ゴ (GO)', mean: 'Belakang / Setelah', level: 'N5' },
        { char: '外', kun: 'soto', on: 'ガイ (GAI)', mean: 'Luar', level: 'N5' },
        { char: '電', kun: '-', on: 'デン (DEN)', mean: 'Listrik', level: 'N5' },
        { char: '車', kun: 'kuruma', on: 'シャ (SHA)', mean: 'Mobil / Roda', level: 'N5' },
        { char: '北', kun: 'kita', on: 'ホク (HOKU)', mean: 'Utara', level: 'N5' },
        { char: '南', kun: 'minami', on: 'ナン (NAN)', mean: 'Selatan', level: 'N5' },
        { char: '東', kun: 'higashi', on: 'トウ (TOU)', mean: 'Timur', level: 'N5' },
        { char: '西', kun: 'nishi', on: 'セイ (SEI)', mean: 'Barat', level: 'N5' },
        { char: '気', kun: '-', on: 'キ (KI)', mean: 'Semangat / Udara', level: 'N5' },
        { char: '天', kun: 'ame', on: 'テン (TEN)', mean: 'Langit', level: 'N5' },
        { char: '空', kun: 'sora', on: 'クウ (KUU)', mean: 'Langit / Kosong', level: 'N5' },
        { char: '白', kun: 'shiro', on: 'ハク (HAKU)', mean: 'Putih', level: 'N5' },
        { char: '赤', kun: 'aka', on: 'セキ (SEKI)', mean: 'Merah', level: 'N5' },
        { char: '青', kun: 'ao', on: 'セイ (SEI)', mean: 'Biru', level: 'N5' },
        { char: '雨', kun: 'ame', on: 'ウ (U)', mean: 'Hujan', level: 'N5' },
        { char: '長', kun: 'naga', on: 'チョウ (CHOU)', mean: 'Panjang / Ketua', level: 'N5' },
        { char: '多', kun: 'oo', on: 'タ (TA)', mean: 'Banyak', level: 'N5' },
        { char: '父', kun: 'chichi', on: 'フ (FU)', mean: 'Ayah', level: 'N5' },
        { char: '母', kun: 'haha', on: 'ボ (BO)', mean: 'Ibu', level: 'N5' },
        { char: '高', kun: 'taka', on: 'コウ (KOU)', mean: 'Tinggi / Mahal', level: 'N5' },
        { char: '安', kun: 'yasu', on: 'アン (AN)', mean: 'Murah / Tenang', level: 'N5' },
        { char: '早', kun: 'haya', on: 'ソウ (SOU)', mean: 'Cepat (Waktu)', level: 'N5' },
        { char: '新', kun: 'atara', on: 'シン (SHIN)', mean: 'Baru', level: 'N5' },
        { char: '古', kun: 'furu', on: 'コ (KO)', mean: 'Tua / Lama', level: 'N5' },
        { char: '正', kun: 'tada', on: 'セイ (SEI)', mean: 'Benar', level: 'N5' },
        { char: '午', kun: '-', on: 'ゴ (GO)', mean: 'Siang', level: 'N5' },
        { char: '休', kun: 'yasu', on: 'キュウ (KYUU)', mean: 'Istirahat', level: 'N5' },
        { char: '少', kun: 'suko / suku', on: 'ショウ (SHOU)', mean: 'Sedikit', level: 'N5' },
        { char: '万', kun: 'yorozu', on: 'マン (MAN)', mean: 'Sepuluh Ribu', level: 'N5' },
        { char: '今', kun: 'ima', on: 'コン (KON)', mean: 'Sekarang', level: 'N5' },
        { char: '社', kun: 'yashiro', on: 'シャ (SHA)', mean: 'Perusahaan / Kuil', level: 'N5' },
        { char: '店', kun: 'mise', on: 'テン (TEN)', mean: 'Toko', level: 'N5' },
        { char: '聞', kun: 'ki', on: 'ブン (BUN)', mean: 'Mendengar', level: 'N5' },
        { char: '買', kun: 'ka', on: 'バイ (BAI)', mean: 'Membeli', level: 'N5' },
        { char: '分', kun: 'wa', on: 'ブン (BUN)', mean: 'Menit / Mengerti', level: 'N5' },

        // N4 - Dasar & Menengah (Total 200 baru untuk melengkapi jadi 300)
        { char: '使', kun: 'tska', on: 'シ (SHI)', mean: 'Menggunakan', level: 'N4' },
        { char: '始', kun: 'haji', on: 'シ (SHI)', mean: 'Mulai', level: 'N4' },
        { char: '終', kun: 'owa', on: 'シュウ (SHUU)', mean: 'Selesai', level: 'N4' },
        { char: '開', kun: 'a', on: 'カイ (KAI)', mean: 'Buka', level: 'N4' },
        { char: '閉', kun: 'shi', on: 'ヘイ (HEI)', mean: 'Tutup', level: 'N4' },
        { char: '問', kun: 'to', on: 'モン (MON)', mean: 'Pertanyaan', level: 'N4' },
        { char: '題', kun: '-', on: 'ダイ (DAI)', mean: 'Topik / Judul', level: 'N4' },
        { char: '待', kun: 'ma', on: 'タイ (TAI)', mean: 'Tunggu', level: 'N4' },
        { char: '持', kun: 'mo', on: 'ジ (JI)', mean: 'Memegang / Mempunyai', level: 'N4' },
        { char: '知', kun: 'shi', on: 'チ (CHI)', mean: 'Tahu', level: 'N4' },
        { char: '答', kun: 'kota', on: 'トウ (TOU)', mean: 'Jawaban', level: 'N4' },
        { char: '考', kun: 'kanga', on: 'コウ (KOU)', mean: 'Berpikir', level: 'N4' },
        { char: '死', kun: 'shi', on: 'シ (SHI)', mean: 'Mati', level: 'N4' },
        { char: '私', kun: 'watashi', on: 'シ (SHI)', mean: 'Saya', level: 'N4' },
        { char: '親', kun: 'oya', on: 'シン (SHIN)', mean: 'Orang Tua / Akrab', level: 'N4' },
        { char: '屋', kun: 'ya', on: 'オク (OKU)', mean: 'Atap / Toko', level: 'N4' },
        { char: '室', kun: 'muro', on: 'シツ (SHITSU)', mean: 'Ruangan', level: 'N4' },
        { char: '家', kun: 'ie / ya', on: 'カ (KA)', mean: 'Rumah / Keluarga', level: 'N4' },
        { char: '場', kun: 'ba', on: 'ジョウ (JOU)', mean: 'Tempat', level: 'N4' },
        { char: '地', kun: '-', on: 'チ (CHI) / ジ (JI)', mean: 'Tanah / Bumi', level: 'N4' },
        { char: '世', kun: 'yo', on: 'セイ (SEI)', mean: 'Dunia / Generasi', level: 'N4' },
        { char: '界', kun: '-', on: 'カイ (KAI)', mean: 'Dunia / Batas', level: 'N4' },
        { char: '道', kun: 'michi', on: 'ドウ (DOU)', mean: 'Jalan', level: 'N4' },
        { char: '歩', kun: 'aru', on: 'ホ (HO)', mean: 'Berjalan', level: 'N4' },
        { char: '走', kun: 'hashi', on: 'ソウ (SOU)', mean: 'Lari', level: 'N4' },
        { char: '止', kun: 'to', on: 'シ (SHI)', mean: 'Berhenti', level: 'N4' },
        { char: '自', kun: 'mizuka', on: 'ジ (JI)', mean: 'Diri Sendiri', level: 'N4' },
        { char: '由', kun: '-', on: 'ユ (YU)', mean: 'Alasan', level: 'N4' },
        { char: '夜', kun: 'yo', on: 'ヤ (YA)', mean: 'Malam', level: 'N4' },
        { char: '朝', kun: 'asa', on: 'チョウ (CHOU)', mean: 'Pagi', level: 'N4' },
        { char: '昼', kun: 'hiru', on: 'チュウ (CHUU)', mean: 'Siang', level: 'N4' },
        { char: '夕', kun: 'yuu', on: 'セキ (SEKI)', mean: 'Sore', level: 'N4' },
        { char: '春', kun: 'haru', on: 'シュン (SHUN)', mean: 'Musim Semi', level: 'N4' },
        { char: '夏', kun: 'natsu', on: 'カ (KA)', mean: 'Musim Panas', level: 'N4' },
        { char: '秋', kun: 'aki', on: 'シュウ (SHUU)', mean: 'Musim Gugur', level: 'N4' },
        { char: '冬', kun: 'fuyu', on: 'トウ (TOU)', mean: 'Musim Dingin', level: 'N4' },
        { char: '風', kun: 'kaze', on: 'フウ (FUU)', mean: 'Angin', level: 'N4' },
        { char: '海', kun: 'umi', on: 'カイ (KAI)', mean: 'Laut', level: 'N4' },
        { char: '光', kun: 'hikari', on: 'コウ (KOU)', mean: 'Cahaya', level: 'N4' },
        { char: '台', kun: '-', on: 'ダイ (DAI)', mean: 'Stand / Rak', level: 'N4' },
        { char: '度', kun: 'tabi', on: 'ド (DO)', mean: 'Derajat / Kali', level: 'N4' },
        { char: '計', kun: 'haka', on: 'ケイ (KEI)', mean: 'Rencana / Ukur', level: 'N4' },
        { char: '教', kun: 'oshi', on: 'キョウ (KYOU)', mean: 'Mengajar', level: 'N4' },
        { char: '強', kun: 'tsuyo', on: 'キョウ (KYOU)', mean: 'Kuat', level: 'N4' },
        { char: '勉', kun: 'tsuto', on: 'ベン (BEN)', mean: 'Berusaha', level: 'N4' },
        { char: '楽', kun: 'tano', on: 'ラク (RAKU)', mean: 'Nyaman / Musik', level: 'N4' },
        { char: '料', kun: '-', on: 'リョウ (RYOU)', mean: 'Bahan / Biaya', level: 'N4' },
        { char: '理', kun: '-', on: 'リ (RI)', mean: 'Alasan / Logika', level: 'N4' },
        { char: '体', kun: 'karada', on: 'タイ (TAI)', mean: 'Tubuh', level: 'N4' },
        { char: '力', kun: 'chikara', on: 'リョク (RYOKU)', mean: 'Tenaga', level: 'N4' },
        { char: '心', kun: 'kokoro', on: 'シン (SHIN)', mean: 'Hati', level: 'N4' },
        { char: '思', kun: 'omo', on: 'シ (SHI)', mean: 'Pikir', level: 'N4' },
        { char: '売', kun: 'u', on: 'バイ (BAI)', mean: 'Jual', level: 'N4' },
        { char: '住', kun: 'su', on: 'ジュウ (JUU)', mean: 'Tinggal', level: 'N4' },
        { char: '洗', kun: 'ara', on: 'セン (SEN)', mean: 'Cuci', level: 'N4' },
        { char: '立', kun: 'ta', on: 'リツ (RITSU)', mean: 'Berdiri', level: 'N4' },
        { char: '歩', kun: 'aru', on: 'ホ (HO)', mean: 'Berjalan', level: 'N4' },
        { char: '急', kun: 'iso', on: 'キュウ (KYUU)', mean: 'Cepat / Buru-buru', level: 'N4' },
        { char: '野', kun: 'no', on: 'ヤ (YA)', mean: 'Lapangan', level: 'N4' },
        { char: '菜', kun: '-', on: 'サイ (SAI)', mean: 'Sayur', level: 'N4' },
        { char: '色', kun: 'iro', on: 'ショク (SHOKU)', mean: 'Warna', level: 'N4' },
        { char: '黒', kun: 'kuro', on: 'コク (KOKU)', mean: 'Hitam', level: 'N4' },
        { char: '町', kun: 'machi', on: 'チョウ (CHOU)', mean: 'Kota', level: 'N4' },
        { char: '村', kun: 'mura', on: 'ソン (SON)', mean: 'Desa', level: 'N4' },
        { char: '京', kun: 'miyako', on: 'キョウ (KYOU)', mean: 'Ibukota', level: 'N4' },
        { char: '都', kun: 'miyako', on: 'ト (TO)', mean: 'Ibukota / Metropolitan', level: 'N4' },
        { char: '会', kun: 'a', on: 'カイ (KAI)', mean: 'Bertemu / Perkumpulan', level: 'N4' },
        { char: '社', kun: 'yashiro', on: 'シャ (SHA)', mean: 'Perusahaan', level: 'N4' },
        { char: '工', kun: '-', on: 'コウ (KOU)', mean: 'Kerja / Teknik', level: 'N4' },
        { char: '作', kun: 'tsuku', on: 'サク (SAKU)', mean: 'Membuat', level: 'N4' },
        { char: '使', kun: 'tska', on: 'シ (SHI)', mean: 'Guna', level: 'N4' },
        { char: '運', kun: 'hako', on: 'ウン (HUN)', mean: 'Keberuntungan / Transportasi', level: 'N4' },
        { char: '動', kun: 'ugo', on: 'ドウ (DOU)', mean: 'Bergerak', level: 'N4' },
        { char: '送', kun: 'oku', on: 'ソウ (SOU)', mean: 'Mengirim', level: 'N4' },
        { char: '切', kun: 'ki', on: 'セツ (SETSU)', mean: 'Potong / Putus', level: 'N4' },
        { char: '借', kun: 'ka', on: 'シャク (SHAKU)', mean: 'Pinjam', level: 'N4' },
        { char: '貸', kun: 'ka', on: 'タイ (TAI)', mean: 'Pinjamkan', level: 'N4' },
        { char: '返', kun: 'kae', on: 'ヘン (HEN)', mean: 'Kembali', level: 'N4' },
        { char: '建', kun: 'ta', on: 'ケン (KEN)', mean: 'Membangun', level: 'N4' },
        { char: '病', kun: 'yama', on: 'ビョウ (BYOU)', mean: 'Sakit', level: 'N4' },
        { char: '院', kun: '-', on: 'イン (IN)', mean: 'Institusi', level: 'N4' },
        { char: '医', kun: '-', on: 'イ (I)', mean: 'Medis', level: 'N4' },
        { char: '者', kun: 'mono', on: 'シャ (SHA)', mean: 'Orang / Profesional', level: 'N4' },
        { char: '体', kun: 'karada', on: 'タイ (TAI)', mean: 'Badan', level: 'N4' },
        { char: '頭', kun: 'atama', on: 'トウ (TOU)', mean: 'Kepala', level: 'N4' },
        { char: '顔', kun: 'kao', on: 'ガン (GAN)', mean: 'Wajah', level: 'N4' },
        { char: '首', kun: 'kubi', on: 'シュ (SHU)', mean: 'Leher', level: 'N4' },
        { char: '心', kun: 'kokoro', on: 'シン (SHIN)', mean: 'Hati / Jiwa', level: 'N4' },
        { char: '度', kun: 'tabi', on: 'ド (DO)', mean: 'Kali / Gelar', level: 'N4' },
        { char: '回', kun: 'mawa', on: 'カイ (KAI)', mean: 'Putar / Kali', level: 'N4' },
        { char: '用', kun: 'mochi', on: 'ヨウ (YOU)', mean: 'Gunakan / Urusan', level: 'N4' },
        { char: '事', kun: 'koto', on: 'ジ (JI)', mean: 'Hal / Urusan', level: 'N4' },
        { char: '和', kun: 'yawa', on: 'ワ (WA)', mean: 'Paz / Jepang', level: 'N4' },
        { char: '洋', kun: '-', on: 'ヨウ (YOU)', mean: 'Samudra / Barat', level: 'N4' },
        { char: '肉', kun: '-', on: 'ニク (NIKU)', mean: 'Daging', level: 'N4' },
        { char: '玉', kun: 'tama', on: 'ギョク (GYOKU)', mean: 'Permata / Bulat', level: 'N4' },
        { char: '茶', kun: '-', on: 'チャ (CHA) / サ (SA)', mean: 'Teh', level: 'N4' },
        { char: '米', kun: 'kome', on: 'マイ (MAI)', mean: 'Beras', level: 'N4' },
        { char: '鳥', kun: 'tori', on: 'チョウ (CHOU)', mean: 'Burung', level: 'N4' },
        { char: '味', kun: 'aji', on: 'ミ (MI)', mean: 'Rasa', level: 'N4' },
        { char: '油', kun: 'abura', on: 'ユ (YU)', mean: 'Minyak', level: 'N4' },
        { char: '紙', kun: 'kami', on: 'シ (SHI)', mean: 'Kertas', level: 'N4' },
        { char: '着', kun: 'ki / tsu', on: 'チャク (CHAKU)', mean: 'Pakai / Sampai', level: 'N4' },
        { char: '服', kun: '-', on: 'フク (FUKU)', mean: 'Pakaian', level: 'N4' },
        { char: '物', kun: 'mono', on: 'ブツ (BUTSU)', mean: 'Benda', level: 'N4' },
        { char: '特', kun: '-', on: 'トク (TOKU)', mean: 'Spesial', level: 'N4' },
        { char: '別', kun: 'wa', on: 'ベツ (BETSU)', mean: 'Lain / Pisah', level: 'N4' },
        { char: '少', kun: 'suku / suko', on: 'ショウ (SHOU)', mean: 'Sedikit', level: 'N4' },
        { char: '多', kun: 'oo', on: 'タ (TA)', mean: 'Banyak', level: 'N4' },
        { char: '広', kun: 'hiro', on: 'コウ (KOU)', mean: 'Luas', level: 'N4' },
        { char: '早', kun: 'haya', on: 'ソウ (SOU)', mean: 'Cepat / Awal', level: 'N4' },
        { char: '止', kun: 'to', on: 'シ (SHI)', mean: 'Berhenti', level: 'N4' },
        { char: '正', kun: 'tada', on: 'セイ (SEI)', mean: 'Benar', level: 'N4' },
        { char: '重', kun: 'omo', on: 'ジュウ (JUU)', mean: 'Berat', level: 'N4' },
        { char: '軽', kun: 'karu', on: 'ケイ (KEI)', mean: 'Ringan', level: 'N4' },
        { char: '弱', kun: 'yowa', on: 'ジャク (JAKU)', mean: 'Lemah', level: 'N4' },
        { char: '強', kun: 'tsuyo', on: 'キョウ (KYOU)', mean: 'Kuat', level: 'N4' },
        { char: '暗', kun: 'kura', on: 'アン (AN)', mean: 'Gelap', level: 'N4' },
        { char: '明', kun: 'aka / a', on: 'メイ (MEI)', mean: 'Terang', level: 'N4' },
        { char: '遠', kun: 'too', on: 'エン (EN)', mean: 'Jauh', level: 'N4' },
        { char: '近', kun: 'chika', on: 'キン (KIN)', mean: 'Dekat', level: 'N4' },
        { char: '太', kun: 'futo', on: 'タイ (TAI)', mean: 'Gemuk', level: 'N4' },
        { char: '細', kun: 'hoso', on: 'サイ (SAI)', mean: 'Tipis', level: 'N4' },
        { char: '研', kun: 'to', on: 'ケン (KEN)', mean: 'Penelitian', level: 'N4' },
        { char: '究', kun: 'kiwa', on: 'キュウ (KYUU)', mean: 'Studi', level: 'N4' },
        { char: '館', kun: '-', on: 'カン (KAN)', mean: 'Gedung', level: 'N4' },
        { char: '図', kun: 'haka', on: 'ズ (ZU)', mean: 'Gambar / Peta', level: 'N4' },
        { char: '銀', kun: '-', on: 'ギン (GIN)', mean: 'Perak', level: 'N4' },
        { char: '銀行', kun: '-', on: 'ギンコウ (GINKOU)', mean: 'Bank', level: 'N4' },
        { char: '写', kun: 'utsu', on: 'シャ (SHA)', mean: 'Salinan / Foto', level: 'N4' },
        { char: '真', kun: 'ma', on: 'シン (SHIN)', mean: 'Benar / Murni', level: 'N4' },
        { char: '台', kun: '-', on: 'ダイ (DAI)', mean: 'Rak / Stand', level: 'N4' },
        { char: '風', kun: 'kaze', on: 'フウ (FUU)', mean: 'Angin', level: 'N4' },
        { char: '船', kun: 'fune', on: 'セン (SEN)', mean: 'Kapal', level: 'N4' },
        { char: '空', kun: 'sora', on: 'クウ (KUU)', mean: 'Langit / Angkasa', level: 'N4' },
        { char: '荷', kun: 'ni', on: 'カ (KA)', mean: 'Beban / Barang', level: 'N4' },

        // N3 - Menengah (Menuju Total 650)
        { char: '政', kun: 'matsurigoto', on: 'セイ (SEI)', mean: 'Politik', level: 'N3' },
        { char: '治', kun: 'na', on: 'ジ (JI) / チ (CHI)', mean: 'Memerintah / Sembuh', level: 'N3' },
        { char: '経', kun: 'he', on: 'ケイ (KEI)', mean: 'Melalui / Ekonomi', level: 'N3' },
        { char: '済', kun: 'su', on: 'サイ (SAI)', mean: 'Selesai / Ekonomi', level: 'N3' },
        { char: '法', kun: 'nori', on: 'ホウ (HOU)', mean: 'Hukum', level: 'N3' },
        { char: '律', kun: '-', on: 'リツ (RITSU)', mean: 'Aturan', level: 'N3' },
        { char: '判', kun: 'waka', on: 'ハン (HAN)', mean: 'Menilai', level: 'N3' },
        { char: '断', kun: 'tata', on: 'ダン (DAN)', mean: 'Memutuskan / Menolak', level: 'N3' },
        { char: '任', kun: 'maka', on: 'ニン (NIN)', mean: 'Tugas / Tanggung Jawab', level: 'N3' },
        { char: '務', kun: 'tsuto', on: 'ム (MU)', mean: 'Tugas', level: 'N3' },
        { char: '警', kun: '-', on: 'ケイ (KEI)', mean: 'Peringatan / Polisi', level: 'N3' },
        { char: '察', kun: '-', on: 'サツ (SATSU)', mean: 'Mengecek / Menebak', level: 'N3' },
        { char: '信', kun: '-', on: 'シン (SHIN)', mean: 'Percaya / Pesan', level: 'N3' },
        { char: '頼', kun: 'tano', on: 'ライ (RAI)', mean: 'Percaya / Meminta', level: 'N3' },
        { char: '容', kun: '-', on: 'ヨウ (YOU)', mean: 'Isi / Wadah', level: 'N3' },
        { char: '疑', kun: 'utaga', on: 'ギ (GI)', mean: 'Ragu', level: 'N3' },
        { char: '解', kun: 'to', on: 'カイ (KAI)', mean: 'Memecahkan / Mengerti', level: 'N3' },
        { char: '説', kun: 'to', on: 'セツ (SETSU)', mean: 'Menjelaskan', level: 'N3' },
        { char: '念', kun: '-', on: 'ネン (NEN)', mean: 'Pikiran / Perasaan', level: 'N3' },
        { char: '機', kun: 'hata', on: 'キ (KI)', mean: 'Mesin / Kesempatan', level: 'N3' },
        { char: '関', kun: 'seki', on: 'カン (KAN)', mean: 'Penghubung / Gerbang', level: 'N3' },
        { char: '係', kun: 'kaka', on: 'ケイ (KEI)', mean: 'Hubungan / Petugas', level: 'N3' },
        { char: '商', kun: 'aki', on: 'ショウ (SHOU)', mean: 'Dagang', level: 'N3' },
        { char: '業', kun: 'waza', on: 'ギョウ (GYOU)', mean: 'Industri / Bisnis', level: 'N3' },
        { char: '情', kun: 'nasa', on: 'ジョウ (JOU)', mean: 'Emosi / Informasi', level: 'N3' },
        { char: '報', kun: 'muku', on: 'ホウ (HOU)', mean: 'Laporan / Balasan', level: 'N3' },
        { char: '告', kun: 'tsuge', on: 'コク (KOKU)', mean: 'Memberitahu', level: 'N3' },
        { char: '支', kun: 'sasa', on: 'シ (SHI)', mean: 'Mendukung', level: 'N3' },
        { char: '願', kun: 'nega', on: 'ガン (GAN)', mean: 'Permohonan', level: 'N3' },
        { char: '資', kun: '-', on: 'シ (SHI)', mean: 'Sumber Daya / Modal', level: 'N3' },
        { char: '個', kun: '-', on: 'コ (KO)', mean: 'Individu', level: 'N3' },
        { char: '製', kun: '-', on: 'セイ (SEI)', mean: 'Memproduksi', level: 'N3' },
        { char: '全', kun: 'matta', on: 'ゼン (ZEN)', mean: 'Seluruh / Semua', level: 'N3' },
        { char: '部', kun: '-', on: 'ブ (BU)', mean: 'Bagian / Departemen', level: 'N3' },
        { char: '必', kun: 'kanara', on: 'ヒツ (HITSU)', mean: 'Pasti / Perlu', level: 'N3' },
        { char: '要', kun: 'ira', on: 'ヨウ (YOU)', mean: 'Penting / Butuh', level: 'N3' },
        { char: '荷', kun: 'ni', on: 'カ (KA)', mean: 'Beban / Barang', level: 'N3' },
        { char: '機', kun: 'hata', on: 'キ (KI)', mean: 'Pesawat / Peluang', level: 'N3' },
        { char: '欠', kun: 'ka', on: 'ケツ (KETSU)', mean: 'Kurang / Cacat', level: 'N3' },
        { char: '次', kun: 'tsugi', on: 'ジ (JI)', mean: 'Berikutnya', level: 'N3' },
        { char: '由', kun: 'yoshi', on: 'ユ (YU)', mean: 'Alasan', level: 'N3' },
        { char: '身', kun: 'mi', on: 'シン (SHIN)', mean: 'Badan / Diri', level: 'N3' },
        { char: '打', kun: 'u', on: 'ダ (DA)', mean: 'Memukul', level: 'N3' },
        { char: '投', kun: 'na', on: 'トウ (TOU)', mean: 'Melempar', level: 'N3' },
        { char: '折', kun: 'o', on: 'セツ (SETSU)', mean: 'Melipat / Patah', level: 'N3' },
        { char: '抜', kun: 'nu', on: 'バツ (BATSU)', mean: 'Mencabut / Melewati', level: 'N3' },
        { char: '抱', kun: 'da /抱か', on: 'ホウ (HOU)', mean: 'Memeluk / Memegang', level: 'N3' },
        { char: '払', kun: 'hara', on: 'フツ (FUTSU)', mean: 'Membayar', level: 'N3' },
        { char: '込', kun: 'ko', on: '-', mean: 'Masuk / Ramai', level: 'N3' },
        { char: '連', kun: 'tsu', on: 'レン (REN)', mean: 'Menghubungkan / Mengambil', level: 'N3' },
        { char: '絡', kun: 'kara', on: 'ラク (ラク)', mean: 'Terjerat / Kontak', level: 'N3' },
        { char: '呼', kun: 'yo', on: 'コ (KO)', mean: 'Memanggil', level: 'N3' },
        { char: '吸', kun: 'su', on: 'キュウ (KYUU)', mean: 'Menyerap / Isap', level: 'N3' },
        { char: '吹', kun: 'fu', on: 'スイ (SUI)', mean: 'Meniup', level: 'N3' },
        { char: '咲', kun: 'sa', on: 'ショウ (SHOU)', mean: 'Mekar', level: 'N3' },
        { char: '守', kun: 'mamo', on: 'シュ (SHU)', mean: 'Menjaga', level: 'N3' },
        { char: '助', kun: 'tasu', on: 'ジョ (JO)', mean: 'Membantu', level: 'N3' },
        { char: '飛', kun: 'to', on: 'ヒ (HI)', mean: 'Terbang', level: 'N3' },
        { char: '運', kun: 'hako', on: 'ウン (UN)', mean: 'Mengangkut / Keberuntungan', level: 'N3' },
        { char: '乗', kun: 'no', on: 'ジョウ (JOU)', mean: 'Naik (Kendaraan)', level: 'N3' },
        { char: '配', kun: 'kuba', on: 'ハイ (HAI)', mean: 'Membagikan', level: 'N3' },

        // N2 - Menengah-Lanjut (Menuju Total 1.000)
        { char: '震', kun: 'furu', on: 'シン (SHIN)', mean: 'Gempa / Getar', level: 'N2' },
        { char: '憲', kun: '-', on: 'KEN (KEN)', mean: 'Konstitusi', level: 'N2' },
        { char: '総', kun: 'sube', on: 'ソウ (SOU)', mean: 'Umum / Total', level: 'N2' },
        { char: '練', kun: 'ne', on: 'REN (REN)', mean: 'Latihan / Poles', level: 'N2' },
        { char: '維', kun: '-', on: 'イ (I)', mean: 'Memelihara / Serat', level: 'N2' },
        { char: '護', kun: 'mamo', on: 'ゴ (GO)', mean: 'Melindungi', level: 'N2' },
        { char: '態', kun: '-', on: 'タイ (TAI)', mean: 'Kondisi / Penampilan', level: 'N2' },
        { char: '視', kun: 'mi', on: 'シ (SHI)', mean: 'Melihat / Inspeksi', level: 'N2' },
        { char: '績', kun: '-', on: 'セキ (SEKI)', mean: 'Pencapaian / Produk', level: 'N2' },
        { char: '格', kun: '-', on: 'カク (KAKU)', mean: 'Status / Standar', level: 'N2' },
        { char: '規', kun: '-', on: 'キ (KI)', mean: 'Aturan / Standar', level: 'N2' },
        { char: '模', kun: '-', on: 'モ (MO) / ボ (BO)', mean: 'Model / Tiru', level: 'N2' },
        { char: '証', kun: 'aka', on: 'ショウ (SHOU)', mean: 'Bukti / Sertifikat', level: 'N2' },
        { char: '援', kun: '-', on: 'エン (EN)', mean: 'Bantuan / Dukungan', level: 'N2' },
        { char: '施', kun: 'hodo', on: 'シ (SHI) / セ (SE)', mean: 'Melaksanakan / Memberi', level: 'N2' },
        { char: '設', kun: 'mouke', on: 'セツ (SETSU)', mean: 'Membangun / Menyiapkan', level: 'N2' },
        { char: '境', kun: 'sakai', on: 'キョウ (KYOU)', mean: 'Batas / Lingkungan', level: 'N2' },
        { char: '導', kun: 'michi', on: 'ドウ (DOU)', mean: 'Memimpin', level: 'N2' },
        { char: '刊', kun: '-', on: 'カン (KAN)', mean: 'Menerbitkan', level: 'N2' },
        { char: '象', kun: '-', on: 'ショウ (SHOU) / ゾウ (ZOU)', mean: 'Fenomena / Gajah', level: 'N2' },
        { char: '徴', kun: '-', on: 'チョウ (CHOU)', mean: 'Indikasi / Kumpul', level: 'N2' },
        { char: '延', kun: 'no', on: 'エン (EN)', mean: 'Memperpanjang', level: 'N2' },
        { char: '招', kun: 'mana', on: 'ショウ (SHOU)', mean: 'Mengundang', level: 'N2' },
        { char: '担', kun: 'nina', on: 'タン (TAN)', mean: 'Memikul / Bertanggung Jawab', level: 'N2' },
        { char: '拠', kun: 'yo', on: 'キョ (KYO) / コ (KO)', mean: 'Dasar / Pijakan', level: 'N2' },
        { char: '獲', kun: 'e', on: 'カク (KAKU)', mean: 'Menangkap / Memperoleh', level: 'N2' },
        { char: '録', kun: '-', on: 'ロク (ROKU)', mean: 'Merekam', level: 'N2' },
        { char: '採', kun: 'to', on: 'サイ (SAI)', mean: 'Mengambil / Mengadopsi', level: 'N2' },
        { char: '援', kun: '-', on: 'エン (EN)', mean: 'Dukungan', level: 'N2' },
        { char: '販', kun: '-', on: 'ハン (HAN)', mean: 'Menjual / Pemasaran', level: 'N2' },
        { char: '購', kun: '-', on: 'コウ (KOU)', mean: 'Membeli', level: 'N2' },
        { char: '築', kun: 'kizu', on: 'チク (CHIKU)', mean: 'Membangun', level: 'N2' },
        { char: '織', kun: 'o', on: 'シキ (SHIKI)', mean: 'Menenun / Organisasi', level: 'N2' },
        { char: '編', kun: 'a', on: 'ヘン (HEN)', mean: 'Menyusun / Merajut', level: 'N2' },
        { char: '縮', kun: 'chiji', on: 'シュク (SHUKU)', mean: 'Menyusut', level: 'N2' },
        { char: '及', kun: 'oyo', on: 'キュウ (KYUU)', mean: 'Mencapai / Dan', level: 'N2' },
        { char: '拠', kun: 'yo', on: 'キョ (KYO)', mean: 'Dasar', level: 'N2' },
        { char: '占', kun: 'ura / shi', on: 'セン (SEN)', mean: 'Meramal / Menempati', level: 'N2' },
        { char: '述', kun: 'no', on: 'ジュツ (JUTSU)', mean: 'Menyatakan', level: 'N2' },
        { char: '掛', kun: 'ka', on: '-', mean: 'Menggantung / Terlibat', level: 'N2' },
        { char: '探', kun: 'saga', on: 'タン (TAN)', mean: 'Mencari / Menyelidiki', level: 'N2' },
        { char: '検', kun: '-', on: 'ケン (KEN)', mean: 'Memeriksa', level: 'N2' },
        { char: '査', kun: '-', on: 'サ (SA)', mean: 'Menyelidiki', level: 'N2' },
        { char: '証', kun: 'aka', on: 'ショウ (SHOU)', mean: 'Bukti', level: 'N2' },
        { char: '鮮', kun: 'aza', on: 'セン (SEN)', mean: 'Segar / Jelas', level: 'N2' },

        // N1 - Mahir (Menuju Total 2.000)
        { char: '鬱', kun: 'fusagi', on: 'ウツ (UTSU)', mean: 'Depresi / Melankolis', level: 'N1' },
        { char: '鑑', kun: 'kanga', on: 'カン (KAN)', mean: 'Spekimen / Cermin', level: 'N1' },
        { char: '醸', kun: 'kamo', on: 'ジョウ (JOU)', mean: 'Menyeduh', level: 'N1' },
        { char: '嘱', kun: '-', on: 'ショク (SHOKU)', mean: 'Meminta / Memesan', level: 'N1' },
        { char: '嘲', kun: 'aza', on: 'チョウ (CHOU)', mean: 'Mengejek', level: 'N1' },
        { char: '憚', kun: 'habaka', on: 'タン (TAN)', mean: 'Ragu / Takut', level: 'N1' },
        { char: '恣', kun: 'hoshiimama', on: 'シ (SHI)', mean: 'Egois / Bebas', level: 'N1' },
        { char: '慄', kun: 'onono', on: 'リツ (RITSU)', mean: 'Gemetar (Takut)', level: 'N1' },
        { char: '慶', kun: 'yoroko', on: 'ケイ (KEI)', mean: 'Kegembiraan', level: 'N1' },
        { char: '憧', kun: 'akoga', on: 'ショウ (SHOU)', mean: 'Aspirasi / Rindu', level: 'N1' },
        { char: '緻', kun: '-', on: 'チ (CHI)', mean: 'Halus / Teliti', level: 'N1' },
        { char: '諧', kun: '-', on: 'カイ (KAI)', mean: 'Harmoni / Lelucon', level: 'N1' },
        { char: '誰', kun: 'dare', on: 'スイ (SUI)', mean: 'Siapa', level: 'N1' },
        { char: '諦', kun: 'aki', on: 'テイ (TEI)', mean: 'Menyerah / Pasrah', level: 'N1' },
        { char: '謎', kun: 'nazo', on: '-', mean: 'Misteri / Teka-teki', level: 'N1' },
        { char: '傲', kun: 'ogo', on: 'ゴウ (GOU)', mean: 'Sombong', level: 'N1' },
        { char: '羨', kun: 'uraya', on: 'セン (セン)', mean: 'Iri', level: 'N1' },
        { char: '厭', kun: 'iya', on: 'エン (EN)', mean: 'Bosan / Jijik', level: 'N1' },
        { char: '怨', kun: 'ura', on: 'エン (EN) / オン (ON)', mean: 'Dendam', level: 'N1' },
        { char: '蔑', kun: 'sagesu', on: 'ベツ (BETSU)', mean: 'Menghina', level: 'N1' },
        { char: '彙', kun: '-', on: 'イ (I)', mean: 'Kumpulan / Kosakata', level: 'N1' },
        { char: '旺', kun: '-', on: 'オウ (OU)', mean: 'Bersemangat / Makmur', level: 'N1' },
        { char: '蓋', kun: 'futa', on: 'ガイ (GAI)', mean: 'Tutup / Kerudung', level: 'N1' },
        { char: '骸', kun: 'mukuro', on: 'ガイ (GAI)', mean: 'Kerangka / Jasad', level: 'N1' },
        { char: '顎', kun: 'ago', on: 'ガク (GAKU)', mean: 'Dagu / Rahang', level: 'N1' },
        { char: '僅', kun: 'wazu', on: 'キン (KIN)', mean: 'Sedikit / Nyaris', level: 'N1' },
        { char: '憬', kun: 'akoga', on: 'ケイ (KEI)', mean: 'Mengagumi / Rindu', level: 'N1' },
        { char: '稽', kun: '-', on: 'ケイ (KEI)', mean: 'Studi / Praktek', level: 'N1' },
        { char: '拳', kun: 'kobushi', on: 'ケン (KEN)', mean: 'Tinju', level: 'N1' },
        { char: '鍵', kun: 'kagi', on: 'ケン (KEN)', mean: 'Kunci', level: 'N1' },
        { char: '傲', kun: 'ogo', on: 'ゴウ (GOU)', mean: 'Keangkuhan', level: 'N1' },
        { char: '喉', kun: 'nodo', on: 'コウ (KOU)', mean: 'Tenggorokan', level: 'N1' },
        { char: '索引', kun: '-', on: 'サクイン (SAKUIN)', mean: 'Indeks', level: 'N1' },
        { char: '叱', kun: 'shika', on: 'シツ (SHITSU)', mean: 'Memarahi', level: 'N1' },
        { char: '腫', kun: 'ha', on: 'シュ (SHU)', mean: 'Bengkak', level: 'N1' },
        { char: '羨', kun: 'uraya', on: 'セン (SEN)', mean: 'Iri Hati', level: 'N1' },
        { char: '踪', kun: '-', on: 'ソウ (SOU)', mean: 'Jejak', level: 'N1' },
        { char: '捗', kun: 'haka', on: 'チョク (CHOKU)', mean: 'Kemajuan', level: 'N1' },
        { char: '溺', kun: 'obo', on: 'デキ (DEKI)', mean: 'Tenggelam / Kecanduan', level: 'N1' },
        { char: '訃', kun: '-', on: 'フ (FU)', mean: 'Berita Kematian', level: 'N1' },
        { char: '弄', kun: 'moteaso', on: 'ロウ (ROU)', mean: 'Mempermainkan', level: 'N1' },
        { char: '歪', kun: 'yuga', on: 'ワイ (WAI)', mean: 'Distorsi / Miring', level: 'N1' }
    ],

    conversations: [
        {
            title: 'Perkenalan Diri',
            dialogs: [
                { role: 'ai', jp: 'はじめまして。', ro: 'Hajimemashite.', en: 'Senang bertemu denganmu.' },
                { role: 'user', jp: 'はじめまして。わたしは アリ です。', ro: 'Hajimemashite. Watashi wa Ari desu.', en: 'Senang bertemu denganmu juga. Saya Ari.' },
                { role: 'ai', jp: 'どちらから ですか？', ro: 'Dochira kara desu ka?', en: 'Dari mana asalmu?' },
                { role: 'user', jp: 'インドネシア から きました。', ro: 'Indoneshia kara kimashita.', en: 'Saya datang dari Indonesia.' }
            ]
        },
        {
            title: 'Memesan Makan',
            dialogs: [
                { role: 'ai', jp: 'いらっしゃいませ。', ro: 'Irasshaimase.', en: 'Selamat datang.' },
                { role: 'user', jp: 'メニューを おねがいします。', ro: 'Menyuu o Onegaishimasu.', en: 'Minta menunya.' },
                { role: 'ai', jp: 'はい、どうぞ。', ro: 'Hai, douzo.', en: 'Baik, silakan.' },
                { role: 'user', jp: 'これと これを ください。', ro: 'Kore to kore o kudasai.', en: 'Minta ini dan ini.' },
                { role: 'ai', jp: 'かしこまりました。', ro: 'Kashikomarimashita.', en: 'Baik, dimengerti.' }
            ]
        },
        {
            title: 'Menanyakan Jalan',
            dialogs: [
                { role: 'user', jp: 'すみません、えきは どこですか？', ro: 'Sumimasen, eki wa doko desu ka?', en: 'Permisi, stasiun ada di mana?' },
                { role: 'ai', jp: 'あそこに ありますよ。', ro: 'Asoko ni arimasu yo.', en: 'Ada di sebelah sana loh.' },
                { role: 'user', jp: 'あるいて いけますか？', ro: 'Aruite ikemasu ka?', en: 'Apakah bisa pergi dengan jalan kaki?' },
                { role: 'ai', jp: 'はい、５ふん くらいです。', ro: 'Hai, go-fun kurai desu.', en: 'Ya, kira-kira 5 menit.' },
                { role: 'user', jp: 'ありがとうございます。', ro: 'Arigatou gozaimasu.', en: 'Terima kasih.' }
            ]
        },
        {
            title: 'Hobi & Kegemaran',
            dialogs: [
                { role: 'ai', jp: 'しゅみは なんですか？', ro: 'Shumi wa nan desu ka?', en: 'Apa hobimu?' },
                { role: 'user', jp: 'わたしの しゅみは サッカーです。', ro: 'Watashi no shumi wa sakkaa desu.', en: 'Hobi saya adalah sepak bola.' },
                { role: 'ai', jp: 'そうですか！ スポーツが すきですか？', ro: 'Sou desu ka! Supootsu ga suki desu ka?', en: 'Oh begitu! Apa kamu suka olahraga?' },
                { role: 'user', jp: 'はい、とても すきです。', ro: 'Hai, totemo suki desu.', en: 'Ya, sangat suka.' }
            ]
        },
        {
            title: 'Cuaca Hari Ini',
            dialogs: [
                { role: 'user', jp: 'きょうは いい てんきですね。', ro: 'Kyou wa ii tenki desu ne.', en: 'Hari ini cuacanya bagus ya.' },
                { role: 'ai', jp: 'そうですね。でも、ちょっと あついです。', ro: 'Sou desu ne. Demo, chotto atsui desu.', en: 'Benar ya. Tapi, sedikit panas.' },
                { role: 'user', jp: 'あしたの てんきは どうですか？', ro: 'Ashita no tenki wa dou desu ka?', en: 'Bagaimana dengan cuaca besok?' },
                { role: 'ai', jp: 'あしたは あめが ふるかもしれません。', ro: 'Ashita wa ame ga furu kamoshiremasen.', en: 'Besok mungkin akan turun hujan.' }
            ]
        },
        {
            title: 'Menanyakan Waktu',
            dialogs: [
                { role: 'user', jp: 'いま なんじですか？', ro: 'Ima nan-ji desu ka?', en: 'Sekarang jam berapa?' },
                { role: 'ai', jp: 'ごぜん １０じ じゅっぷんです。', ro: 'Gozen juu-ji juppun desu.', en: 'Jam 10 lewat 10 pagi.' },
                { role: 'user', jp: 'かいぎは なんじからですか？', ro: 'Kaigi wa nan-ji kara desu ka?', en: 'Rapatnya mulai jam berapa?' },
                { role: 'ai', jp: '１１じはんです。', ro: 'Juu-ichi-ji han desu.', en: 'Jam 11 lewat 30 (setengah 12).' }
            ]
        },
        {
            title: 'Belanja di Toko',
            dialogs: [
                { role: 'user', jp: 'すみません、これは いくらですか？', ro: 'Sumimasen, kore wa ikura desu ka?', en: 'Permisi, ini harganya berapa?' },
                { role: 'ai', jp: 'それは ３０００えんです。', ro: 'Sore wa san-zen en desu.', en: 'Itu harganya 3000 yen.' },
                { role: 'user', jp: 'じゃあ, これを ください。', ro: 'Jaa, kore o kudasai.', en: 'Kalau begitu, saya beli yang ini.' },
                { role: 'ai', jp: 'ありがとうございます。', ro: 'Arigatou gozaimasu.', en: 'Terima kasih banyak.' }
            ]
        },
        {
            title: 'Di Sekolah',
            dialogs: [
                { role: 'ai', jp: 'しゅくだいは おわりましたか？', ro: 'Shukudai wa owarimashita ka?', en: 'Apakah PR-nya sudah selesai?' },
                { role: 'user', jp: 'はい, ほとんど おわりました。', ro: 'Hai, hotondo owarimashita.', en: 'Ya, hampir selesai.' },
                { role: 'ai', jp: 'むずかしかったですか？', ro: 'Mazukashikatta desu ka?', en: 'Apakah sulit?' },
                { role: 'user', jp: 'いいえ, かんたんでした。', ro: 'Iie, kantan deshita.', en: 'Tidak, cukup mudah.' }
            ]
        },
        {
            title: 'Rencana Akhir Pekan',
            dialogs: [
                { role: 'user', jp: 'しゅうまつ なにを しますか？', ro: 'Shuumatsu nani o shimasu ka?', en: 'Apa yang akan kamu lakukan akhir pekan ini?' },
                { role: 'ai', jp: 'ともだちと えいがを みに いきます。', ro: 'Tomodachi to eiga o mi ni ikimasu.', en: 'Saya akan pergi menonton film dengan teman.' },
                { role: 'user', jp: 'いいですね！ なにを みますか？', ro: 'Ii desu ne! Nani o mimasu ka?', en: 'Bagus ya! Mau nonton apa?' },
                { role: 'ai', jp: 'アニメを みます。', ro: 'Anime o mimasu.', en: 'Mau nonton Anime.' }
            ]
        },
        {
            title: 'Di Rumah Sakit',
            dialogs: [
                { role: 'ai', jp: 'どうしましたか？', ro: 'Dou shimashita ka?', en: 'Ada apa? (Apa yang dirasakan?)' },
                { role: 'user', jp: 'きのうから あたまが いいたいです。', ro: 'Kinou kara atama ga itai desu.', en: 'Sejak kemarin kepala saya sakit.' },
                { role: 'ai', jp: 'ねつは ありますか？', ro: 'Netsu wa arimasu ka?', en: 'Apakah ada demam?' },
                { role: 'user', jp: 'はい, ３８ど あります。', ro: 'Hai, san-juu-hachi do arimasu.', en: 'Ya, ada 38 derajat.' }
            ]
        },
        {
            title: 'Ulang Tahun',
            dialogs: [
                { role: 'user', jp: 'たんじょうび おめでとう！', ro: 'Tanjoubi omedetou!', en: 'Selamat ulang tahun!' },
                { role: 'ai', jp: 'ありがとうございます！', ro: 'Arigatou gozaimasu!', en: 'Terima kasih banyak!' },
                { role: 'user', jp: 'プレゼントです。どうぞ。', ro: 'Purezento desu. Douzo.', en: 'Ini hadiahnya. Silakan.' },
                { role: 'ai', jp: 'わあ, きれいですね。うれしいです。', ro: 'Waa, kirei desu ne. Ureshii desu.', en: 'Wah, indah ya. Saya senang sekali.' }
            ]
        },
        {
            title: 'Hobi Musik',
            dialogs: [
                { role: 'ai', jp: 'どんな おんがくが すきですか？', ro: 'Donna ongaku ga suki desu ka?', en: 'Musik seperti apa yang kamu suka?' },
                { role: 'user', jp: 'Ｊポップが とても すきです。', ro: 'Jei-poppu ga totemo suki desu.', en: 'Saya sangat suka J-Pop.' },
                { role: 'ai', jp: 'がっきを ひくことが できますか？', ro: 'Gakki o hiku koto ga dekimasu ka?', en: 'Apakah kamu bisa bermain alat musik?' },
                { role: 'user', jp: 'はい, ギターが すこし できます。', ro: 'Hai, gitaa ga sukoshi dekimasu.', en: 'Ya, saya bisa main gitar sedikit.' }
            ]
        },
        {
            title: 'Musim di Jepang',
            dialogs: [
                { role: 'user', jp: 'にほんの なつは どうですか？', ro: 'Nihon no natsu wa dou desu ka?', en: 'Bagaimana musim panas di Jepang?' },
                { role: 'ai', jp: 'とても あついです。でも、まつりが たのしいですよ。', ro: 'Totemo atsui desu. Demo, matsuri ga tanoshii desu yo.', en: 'Sangat panas. Tapi, festivalnya menyenangkan loh.' },
                { role: 'user', jp: 'どの きせつが いちばん すきですか？', ro: 'Dono kisetsu ga ichiban suki desu ka?', en: 'Musim mana yang paling kamu sukai?' },
                { role: 'ai', jp: 'はるが いちばん すきです。さくらが きれいですから。', ro: 'Haru ga ichiban suki desu. Sakura ga kirei desu kara.', en: 'Saya paling suka musim semi. Karena sakuranya indah.' }
            ]
        },
        {
            title: 'Mencari Kerja',
            dialogs: [
                { role: 'user', jp: 'アルバイトを さがしています。', ro: 'Arubaito o sagashite imasu.', en: 'Saya sedang mencari kerja paruh waktu.' },
                { role: 'ai', jp: 'どんな しごとが いいですか？', ro: 'Donna shigoto ga ii desu ka?', en: 'Pekerjaan seperti apa yang bagus?' },
                { role: 'user', jp: 'レストランの しごとが したいです。', ro: 'Resutoran no shigoto ga shitai desu.', en: 'Saya ingin bekerja di restoran.' },
                { role: 'ai', jp: 'あそこで ぼしゅうして いますよ。', ro: 'Asoko de boshuu shite imasu yo.', en: 'Di sana sedang ada lowongan loh.' }
            ]
        },
        {
            title: 'Memasak di Dapur',
            dialogs: [
                { role: 'ai', jp: 'きょうは なにを つくりますか？', ro: 'Kyou wa nani o tsukurimasu ka?', en: 'Hari ini mau masak apa?' },
                { role: 'user', jp: 'カレーを つくります。', ro: 'Karee o tsukurimasu.', en: 'Mau masak kari.' },
                { role: 'ai', jp: 'てつだいましょうか？', ro: 'Tetsudaimashou ka?', en: 'Boleh saya bantu?' },
                { role: 'user', jp: 'はい, やさいを きってください。', ro: 'Hai, yasai o kitte kudasai.', en: 'Ya, tolong potong sayurannya.' }
            ]
        },
        {
            title: 'Meminjam Buku',
            dialogs: [
                { role: 'user', jp: 'この 本を かりても いいですか？', ro: 'Kono hon o karite mo ii desu ka?', en: 'Bolehkan saya meminjam buku ini?' },
                { role: 'ai', jp: 'はい, いいですよ。いつ かえしますか？', ro: 'Hai, ii desu yo. Itsu kaeshimasu ka?', en: 'Ya, boleh. Kapan akan dikembalikan?' },
                { role: 'user', jp: 'らいしゅうの げつようびに かえします。', ro: 'Raishuu no getsuyoubi ni kaeshimasu.', en: 'Akan dikembalikan senin depan.' },
                { role: 'ai', jp: 'わかりました。', ro: 'Wakarimashita.', en: 'Baik, dimengerti.' }
            ]
        },
        {
            title: 'Janji Temu',
            dialogs: [
                { role: 'user', jp: 'あした、あきはばらに いきませんか？', ro: 'Ashita, Akihabara ni ikimasen ka?', en: 'Besok, maukah pergi ke Akihabara?' },
                { role: 'ai', jp: 'いいですね。なんじに あいましょうか？', ro: 'Ii desu ne. Nan-ji ni aimashou ka?', en: 'Boleh juga. Jam berapa kita bertemu?' },
                { role: 'user', jp: 'えきで １じに あいましょう。', ro: 'Eki de ichi-ji ni aimashou.', en: 'Mari bertemu di stasiun jam 1.' },
                { role: 'ai', jp: 'わかりました。たのしみです！', ro: 'Wakarimashita. Tanoshimi desu!', en: 'Siap. Saya menantikannya!' }
            ]
        },
        {
            title: 'Liburan ke Pantai',
            dialogs: [
                { role: 'user', jp: 'なつやすみに うみに いきませんか？', ro: 'Natsuyasumi ni umi ni ikimasen ka?', en: 'Maukah pergi ke laut saat libur musim panas?' },
                { role: 'ai', jp: 'いいですね！ どこが いいですか？', ro: 'Ii desu ne! Doko ga ii desu ka?', en: 'Bagus ya! Di mana bagusnya?' },
                { role: 'user', jp: 'おきなわが いいとおもいます。うみが きれいです。', ro: 'Okinawa ga ii to omoimasu. Umi ga kirei desu.', en: 'Saya rasa Okinawa bagus. Lautnya indah.' },
                { role: 'ai', jp: 'そうですね。おきなわに いきましょう！', ro: 'Sou desu ne. Okinawa ni ikimashou!', en: 'Benar ya. Mari pergi ke Okinawa!' }
            ]
        },
        {
            title: 'Menjelaskan Keluarga',
            dialogs: [
                { role: 'ai', jp: 'ごかぞくは なんにん ですか？', ro: 'Go-kazoku wa nan-nin desu ka?', en: 'Ada berapa orang di keluargamu?' },
                { role: 'user', jp: '４にん です。ちちと ははと あねが います。', ro: 'Yo-nin desu. Chichi to haha to ane ga imasu.', en: 'Ada 4 orang. Ada Ayah, Ibu, dan kakak perempuan.' },
                { role: 'ai', jp: 'おねえさんは おいくつですか？', ro: 'Onee-san wa o-ikutsu desu ka?', en: 'Kakak perempuanmu umur berapa?' },
                { role: 'user', jp: '２２さいです。がくせいです。', ro: 'Ni-juu-ni sai desu. Gakusei desu.', en: '22 tahun. Seorang mahasiswa.' }
            ]
        },
        {
            title: 'Transportasi Umum',
            dialogs: [ // Corrected 'dialog' to 'dialogs'
                { role: 'user', jp: 'この バスは しんじゅくに いきますか？', ro: 'Kono basu wa Shinjuku ni ikimasu ka?', en: 'Apakah bus ini pergi ke Shinjuku?' },
                { role: 'ai', jp: 'はい, いきますよ。', ro: 'Hai, ikimasu yo.', en: 'Ya, pergi (lewat) kok.' },
                { role: 'user', jp: 'いくら ですか？', ro: 'Ikura desu ka?', en: 'Berapa harganya?' },
                { role: 'ai', jp: '２１０えん です。', ro: 'Ni-juu-ichi-juu en desu.', en: '210 yen.' }
            ]
        },
        {
            title: 'Kegiatan Pagi Hari',
            dialogs: [
                { role: 'ai', jp: 'まいあさ なんじに おきますか？', ro: 'Maiasa nan-ji ni okimasu ka?', en: 'Setiap pagi bangun jam berapa?' },
                { role: 'user', jp: '６じに おきます。それから、じょぎんぐを します。', ro: 'Roku-ji ni okimasu. Sore kara, jogingu o shimasu.', en: 'Bangun jam 6. Setelah itu, jogging.' },
                { role: 'ai', jp: 'すごいですね！ あさごはんは たべますか？', ro: 'Sugoi desu ne! Asa-gohan wa tabemasu ka?', en: 'Hebat ya! Apakah makan sarapan?' },
                { role: 'user', jp: 'はい, いつmいつも たべます。', ro: 'Hai, itsumo tabemasu.', en: 'Ya, selalu makan.' }
            ]
        },
        {
            title: 'Menanyakan Alamat',
            dialogs: [
                { role: 'user', jp: 'すみません、ここは どこですか？', ro: 'Sumimasen, koko wa doko desu ka?', en: 'Permisi, ini di mana ya?' },
                { role: 'ai', jp: 'ここは さくらどおり ですよ。', ro: 'Koko wa Sakura-doori desu yo.', en: 'Ini adalah Jalan Sakura loh.' },
                { role: 'user', jp: 'しぶやくやくしょは どこに ありますか？', ro: 'Shibuya-kuyakusho wa doko ni arimasu ka?', en: 'Kantor distrik Shibuya ada di mana?' },
                { role: 'ai', jp: 'この みちを まっすぐ いってください。', ro: 'Kono michi o massugu itte kudasai.', en: 'Tolong jalan lurus di jalan ini.' }
            ]
        },
        {
            title: 'Membeli Tiket Kereta',
            dialogs: [
                { role: 'user', jp: 'きょうとまでの チケットを ２まい ください。', ro: 'Kyouto made no chiketto o ni-mai kudasai.', en: 'Minta 2 tiket sampai Kyoto.' },
                { role: 'ai', jp: 'かたみちですか？ おうふくですか？', ro: 'Katamichi desu ka? Oufuku desu ka?', en: 'Sekali jalan atau pulang-pergi?' },
                { role: 'user', jp: 'おうふくで おねがいします。', ro: 'Oufuku de onegaishimasu.', en: 'Minta yang pulang-pergi.' },
                { role: 'ai', jp: 'ぜんぶで １６０００えんです。', ro: 'Zenbu de ichi-man roku-sen en desu.', en: 'Totalnya 16.000 yen.' }
            ]
        },
        {
            title: 'Cuaca di Akhir Pekan',
            dialogs: [
                { role: 'ai', jp: 'しゅうまつの てんきは どうでしょうか。', ro: 'Shuumatsu no tenki wa dou deshou ka.', en: 'Bagaimana kira-kira cuaca akhir pekan nanti.' },
                { role: 'user', jp: 'てんきよほうでは はれだそうです。', ro: 'Tenki-yohou de wa hare da sou desu.', en: 'Menurut ramalan cuaca katanya akan cerah.' },
                { role: 'ai', jp: 'よかったですね。ピクニックに いきましょう。', ro: 'Yokatta desu ne. Pikunikku ni ikimashou.', en: 'Syukurlah ya. Mari pergi piknik.' },
                { role: 'user', jp: 'いいですね。たのしみに しています。', ro: 'Ii desu ne. Tanoshimi ni shite imasu.', en: 'Ide bagus. Saya menantikannya.' }
            ]
        },
        {
            title: 'Memesan Hotel',
            dialogs: [
                { role: 'ai', jp: 'はい, さくらホテルです。', ro: 'Hai, Sakura Hoteru desu.', en: 'Ya, dengan Sakura Hotel.' },
                { role: 'user', jp: 'あした、へやの よやくを したいです。', ro: 'Ashita, heya no yoyaku o shitai desu.', en: 'Saya ingin memesan kamar untuk besok.' },
                { role: 'ai', jp: 'なんにんさま ですか？', ro: 'Nan-nin sama desu ka?', en: 'Untuk berapa orang?' },
                { role: 'user', jp: 'ひとり です。', ro: 'Hitori desu.', en: 'Untuk satu orang.' }
            ]
        },
        {
            title: 'Bertemu Teman Lama',
            dialogs: [
                { role: 'user', jp: 'あ, たなかさん！ おひさしぶりです。', ro: 'A, Tanaka-san! O-hisashiburi desu.', en: 'Ah, Pak Tanaka! Sudah lama tidak bertemu.' },
                { role: 'ai', jp: 'お元気ですか？', ro: 'O-genki desu ka?', en: 'Apa kabar?' },
                { role: 'user', jp: 'はい, げんきです。いま なにを していますか？', ro: 'Hai, genki desu. Ima nani o shite imasu ka?', en: 'Ya, sehat. Sekarang sedang sibuk apa?' },
                { role: 'ai', jp: 'いまは コンピューターの かいしゃで はたらいています。', ro: 'Ima wa konpyuataa no kaisha de hataraite imasu.', en: 'Sekarang saya bekerja di perusahaan komputer.' }
            ]
        },
        {
            title: 'Di Kantor Pos',
            dialogs: [
                { role: 'user', jp: 'これを インドネシアまで おねがいします。', ro: 'Kore o Indoneshia made onegaishimasu.', en: 'Tolong kirim ini sampai ke Indonesia.' },
                { role: 'ai', jp: 'なかに なにが はいっていますか？', ro: 'Naka ni nani ga haitte imasu ka?', en: 'Apa isi di dalamnya?' },
                { role: 'user', jp: 'おかしと プレゼントです。', ro: 'Okashi to purezento desu.', en: 'Camilan dan hadiah.' },
                { role: 'ai', jp: 'はい, こうくうびんで おくりますか？', ro: 'Hai, koukuubin de okurimasu ka?', en: 'Baik, apakah dikirim lewat pos udara?' }
            ]
        }
    ],

    quizzes: {
        dasar: [
            { type: 'choice', question: 'Apa arti dari "ありがとう"?', options: ['Halo', 'Terima Kasih', 'Maaf', 'Selamat Tinggal'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Hiragana dengan Romaji!', pairs: [{ left: 'あ', right: 'a' }, { left: 'い', right: 'i' }, { left: 'う', right: 'u' }, { left: 'え', right: 'e' }] },
            { type: 'choice', question: 'Apa bahasa Jepang dari "Selamat Pagi"?', options: ['Konnichiwa', 'Konbanwa', 'Ohayou', 'Oyasumi'], answer: 2 },
            { type: 'choice', question: 'Manakah yang berarti "Buku"?', options: ['Mizu', 'Hon', 'Sensei', 'Tegami'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Angka dengan Hiragana-nya!', pairs: [{ left: '一', right: 'ichi' }, { left: '二', right: 'ni' }, { left: '三', right: 'san' }, { left: '四', right: 'yon' }] },
            { type: 'choice', question: 'Apa bahasa Jepang dari "Kucing"?', options: ['Inu', 'Neko', 'Tori', 'Sakana'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "さようなら"?', options: ['Halo', 'Sampai Jumpa', 'Maaf', 'Selamat Makan'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Hiragana dengan Bunyinya!', pairs: [{ left: 'か', right: 'ka' }, { left: 'き', right: 'ki' }, { left: 'く', right: 'ku' }, { left: 'け', right: 'ke' }] },
            { type: 'choice', question: 'Manakah yang berarti "Guru"?', options: ['Gakusei', 'Isha', 'Sensei', 'Keisatsu'], answer: 2 },
            { type: 'choice', question: 'Apa arti dari "はい"?', options: ['Tidak', 'Ya', 'Mungkin', 'Bukan'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Angka Dasar!', pairs: [{ left: '五', right: 'go' }, { left: '六', right: 'roku' }, { left: '七', right: 'nana' }, { left: '八', right: 'hachi' }] },
            { type: 'choice', question: 'Apa bahasa Jepang dari "Siswa"?', options: ['Sensei', 'Gakusei', 'Isha', 'Tenin'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "おやすみなさい"?', options: ['Selamat Siang', 'Selamat Malam (Tidur)', 'Selamat Pagi', 'Halo'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Warna Dasar!', pairs: [{ left: 'あか', right: 'Merah' }, { left: 'あお', right: 'Biru' }, { left: 'しろ', right: 'Putih' }, { left: 'くろ', right: 'Hitam' }] },
            { type: 'choice', question: 'Manakah yang berarti "Bunga"?', options: ['Ki', 'Hana', 'Yama', 'Kawa'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "ごめんなさい"?', options: ['Terima Kasih', 'Sama-sama', 'Mohon Maaf', 'Permisi'], answer: 2 },
            { type: 'matching', question: 'Hubungkan Kata Ganti Orang!', pairs: [{ left: 'わたし', right: 'Saya' }, { left: 'あなた', right: 'Kamu' }, { left: 'かれ', right: 'Dia (L)' }, { left: 'かのじょ', right: 'Dia (P)' }] },
            { type: 'choice', question: 'Apa bahasa Jepang dari "Air"?', options: ['Gohan', 'Cha', 'Mizu', 'Osake'], answer: 2 },
            { type: 'choice', question: 'Manakah yang berarti "Gunung"?', options: ['Umi', 'Yama', 'Kawa', 'Machi'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "いただきます"?', options: ['Terima Kasih', 'Selesai Makan', 'Mari Makan', 'Selamat Datang'], answer: 2 }
        ],
        menengah: [
            { type: 'choice', question: 'Manakah yang merupakan "Nomina" (Kata Benda)?', options: ['たべます', 'おいしい', 'くるま', 'とても'], answer: 2 },
            { type: 'matching', question: 'Hubungkan kosakata dengan artinya!', pairs: [{ left: 'せんせい', right: 'Guru' }, { left: 'がくせい', right: 'Siswa' }, { left: 'ほん', right: 'Buku' }, { left: 'みず', right: 'Air' }] },
            { type: 'choice', question: 'Apa arti dari kata kerja "たべます" (Tabemasu)?', options: ['Minum', 'Pergi', 'Makan', 'Tidur'], answer: 2 },
            { type: 'choice', question: 'Lengkapi kalimat: "Mizu o ..." (Minum air)', options: ['Tabemasu', 'Nomimasu', 'Ikimasu', 'Mimasu'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Kata Sifat dengan Lawannya!', pairs: [{ left: 'たかい (Mahal)', right: 'やすい (Murah)' }, { left: 'おおきい (Besar)', right: 'ちいさい (Kecil)' }, { left: 'あつい (Panas)', right: 'さむい (Dingin)' }, { left: 'いい (Baik)', right: 'わるい (Buruk)' }] },
            { type: 'choice', question: 'Apa bentuk lampau dari "いきます" (Ikimasu)?', options: ['いきました', 'いくです', 'いきません', 'いくでした'], answer: 0 },
            { type: 'choice', question: 'Partikel mana yang menunjukkan waktu?', options: ['wa', 'ni', 'o', 'ga'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Kata Kerja dengan Artinya!', pairs: [{ left: 'はなします', right: 'Berbicara' }, { left: 'よみます', right: 'Membaca' }, { left: 'かきます', right: 'Menulis' }, { left: 'ききます', right: 'Mendengar' }] },
            { type: 'choice', question: 'Manakah yang merupakan Kata Sifat-Na?', options: ['たのしい', 'しずか', 'あかるい', 'しろい'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "とても"?', options: ['Sedikit', 'Sangat', 'Kadang-kadang', 'Mungkin'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Lokasi!', pairs: [{ left: 'ぎんこう', right: 'Bank' }, { left: 'えき', right: 'Stasiun' }, { left: 'がっこう', right: 'Sekolah' }, { left: 'びょういん', right: 'Rumah Sakit' }] },
            { type: 'choice', question: 'Lengkapi: "Pen ... arimasu" (Ada pena)', options: ['wa', 'ni', 'ga', 'o'], answer: 2 },
            { type: 'choice', question: 'Apa arti dari "きのう"?', options: ['Hari ini', 'Besok', 'Kemarin', 'Lusa'], answer: 2 },
            { type: 'matching', question: 'Hubungkan Hari dalam Seminggu!', pairs: [{ left: 'げつようび', right: 'Senin' }, { left: 'かようび', right: 'Selasa' }, { left: 'すいようび', right: 'Rabu' }, { left: 'もくようび', right: 'Kamis' }] },
            { type: 'choice', question: 'Bagaimana cara mengatakan "Tidak Lapar"?', options: ['Onaka ga sukimashita', 'Onaka ga sukimasen', 'Onaka ga ippai desu', 'Onaka ga itai desu'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "ちょっと"?', options: ['Banyak', 'Lama', 'Sebentar / Sedikit', 'Cepat'], answer: 2 },
            { type: 'matching', question: 'Hubungkan Transportasi!', pairs: [{ left: 'でんしゃ', right: 'Kereta' }, { left: 'ひこうき', right: 'Pesawat' }, { left: 'くるま', right: 'Mobil' }, { left: 'じてんしゃ', right: 'Sepeda' }] },
            { type: 'choice', question: 'Manakah partikel kepunyaan?', options: ['wa', 'no', 'ga', 'to'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "にぎやか"?', options: ['Sepi', 'Ramai', 'Bersih', 'Kotor'], answer: 1 },
            { type: 'choice', question: 'Lengkapi: "Ashita kaimono ni ..." (Besok pergi belanja)', options: ['ikimasu', 'ikimashita', 'ikimasen deshita', 'itte'], answer: 0 }
        ],
        lanjut: [
            { type: 'choice', question: 'Apa arti dari "あした べんきょうします"?', options: ['Hari ini belajar', 'Besok belajar', 'Kemarin belajar', 'Minggu depan belajar'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Kanji dengan Kunyomi-nya!', pairs: [{ left: '山', right: 'yama' }, { left: '日', right: 'hi' }, { left: '月', right: 'tsuki' }, { left: '木', right: 'ki' }] },
            { type: 'choice', question: 'Partikel apa yang menunjukkan objek dalam kalimat "Hon ... yomimasu"?', options: ['wa', 'ni', 'o', 'he'], answer: 2 },
            { type: 'choice', question: 'Apa arti dari "どこですか" (Doko desu ka)?', options: ['Apa ini?', 'Siapa itu?', 'Kapan?', 'Di mana?'], answer: 3 },
            { type: 'matching', question: 'Hubungkan Kanji Elemen dengan Artinya!', pairs: [{ left: '火', right: 'Api' }, { left: '水', right: 'Air' }, { left: '土', right: 'Tanah' }, { left: '金', right: 'Emas/Uang' }] },
            { type: 'choice', question: 'Apa perbedaan mendasar antara "Ageru" dan "Kureru"?', options: ['Ageru untuk memberi, Kureru untuk menerima', 'Ageru untuk orang lain, Kureru untuk pembicara/keluarga', 'Tidak ada perbedaan', 'Keduanya berarti menerima'], answer: 1 },
            { type: 'choice', question: 'Manakah bentuk "Te" dari "Tabemasu"?', options: ['Tabete', 'Tabende', 'Tabite', 'Tabette'], answer: 0 },
            { type: 'matching', question: 'Hubungkan Kanji Arah!', pairs: [{ left: '上', right: 'Atas' }, { left: '下', right: 'Bawah' }, { left: '左', right: 'Kiri' }, { left: '右', right: 'Kanan' }] },
            { type: 'choice', question: 'Apa arti dari struktur "~te miru"?', options: ['Pernah melakukan', 'Mencoba melakukan', 'Sedang melakukan', 'Ingin melakukan'], answer: 1 },
            { type: 'choice', question: 'Manakah yang berarti "Mungkin"?', options: ['Tabun', 'Kitto', 'Zettai', 'Moshikasuru to'], answer: 0 },
            { type: 'matching', question: 'Hubungkan Kanji Waktu!', pairs: [{ left: '今', right: 'Sekarang' }, { left: '週', right: 'Minggu' }, { left: '年', right: 'Tahun' }, { left: '間', right: 'Durasi' }] },
            { type: 'choice', question: 'Kapan kita menggunakan "~n desu"?', options: ['Memberikan penjelasan/penekanan', 'Bertanya secara formal', 'Menunjukkan masa depan', 'Hanya untuk tulisan'], answer: 0 },
            { type: 'choice', question: 'Apa arti dari "Issho ni"?', options: ['Sendirian', 'Bersama-sama', 'Kadang-kadang', 'Setiap hari'], answer: 1 },
            { type: 'matching', question: 'Hubungkan Kanji Orang!', pairs: [{ left: '父', right: 'Ayah' }, { left: '母', right: 'Ibu' }, { left: '子', right: 'Anak' }, { left: '友', right: 'Teman' }] },
            { type: 'choice', question: 'Manakah bentuk potensial (bisa) dari "Ikimasu"?', options: ['Ikemasu', 'Ikaremasu', 'Ikasemasu', 'Ikeru'], answer: 0 },
            { type: 'choice', question: 'Apa arti dari "~ba ii desu"?', options: ['Sebaiknya...', 'Boleh...', 'Harus...', 'Tidak perlu...'], answer: 0 },
            { type: 'matching', question: 'Hubungkan Kanji Alam!', pairs: [{ left: '川', right: 'Sungai' }, { left: '海', right: 'Laut' }, { left: '空', right: 'Langit' }, { left: '雨', right: 'Hujan' }] },
            { type: 'choice', question: 'Apa fungsi partikel "mo" dlm kalimat?', options: ['Sebagai subjek', 'Artinya "Juga"', 'Menunjukkan tempat', 'Menunjukkan waktu'], answer: 1 },
            { type: 'choice', question: 'Apa arti dari "Taihen desu ne"?', options: ['Bagus ya', 'Sulit/Berat ya (Simpati)', 'Mudah ya', 'Cepat ya'], answer: 1 },
            { type: 'choice', question: 'Manakah yang merupakan bentuk sopan (Keigo) dari "Ikimasu/Kimasu"?', options: ['Irasshaimasu', 'Moushimasu', 'Itadakimasu', 'Oshiemasu'], answer: 0 }
        ]
    },
    listeningQuest: [
        { question: 'Dengarkan suara berikut. Karakter hiragana apa ini?', audioText: 'あ', options: ['か', 'い', 'う', 'あ'], answer: 3 },
        { question: 'Pilih arti dari sapaan yang Anda dengar:', audioText: 'こんにちは', options: ['Selamat Pagi', 'Apa Kabar', 'Halo / Selamat Siang', 'Terima Kasih'], answer: 2 },
        { question: 'Apa yang diminta dalam audio ini?', audioText: 'メニューを おねがいします', options: ['Minta air', 'Minta menu', 'Minta bon', 'Minta maaf'], answer: 1 },
        { question: 'Di mana lokasi yang disebutkan?', audioText: 'トイレは どこですか', options: ['Stasiun', 'Sekolah', 'Rumah', 'Toilet'], answer: 3 },
        { question: 'Dengarkan kata ini dan pilih artinya:', audioText: 'すみません', options: ['Maaf / Permisi', 'Terima Kasih', 'Sama-sama', 'Selamat Tinggal'], answer: 0 },
        { question: 'Apa ungkapan terima kasih yang formal?', audioText: 'ありがとうございます', options: ['Arigatou', 'Doumo', 'Arigatou Gozaimasu', 'Iie'], answer: 2 },
        { question: 'Pilih profesi yang disebutkan:', audioText: 'わたしは がくせいです', options: ['Guru', 'Siswa', 'Dokter', 'Polisi'], answer: 1 },
        { question: 'Angka berapa yang disebutkan?', audioText: 'いち、に、さん', options: ['1, 2, 3', '4, 5, 6', '7, 8, 9', '0'], answer: 0 },
        { question: 'Benda apa yang disebutkan?', audioText: 'これは ほんです', options: ['Pena', 'Tas', 'Buku', 'Kertas'], answer: 2 },
        { question: 'Waktu apa yang disebutkan?', audioText: 'いま じゅうじです', options: ['Jam 9', 'Jam 10', 'Jam 11', 'Jam 12'], answer: 1 },
        { question: 'Dengarkan hari yang disebutkan:', audioText: 'きょうは にちようびです', options: ['Senin', 'Sabtu', 'Minggu', 'Jumat'], answer: 2 },
        { question: 'Sebutkan warna yang Anda dengar:', audioText: 'あかい くるま', options: ['Merah', 'Biru', 'Kuning', 'Hijau'], answer: 0 },
        { question: 'Apa yang ingin dilakukan pembicara?', audioText: 'みずを のみたいです', options: ['Makan', 'Minum air', 'Tidur', 'Pergi'], answer: 1 },
        { question: 'Dengarkan arah yang disebutkan:', audioText: 'みぎに まがってください', options: ['Kiri', 'Kanan', 'Lurus', 'Belakang'], answer: 1 },
        { question: 'Apa hobi yang disebutkan?', audioText: 'しゅみは どくしょです', options: ['Olahraga', 'Musik', 'Membaca', 'Memasak'], answer: 2 },
        { question: 'Siapa yang dibicarakan?', audioText: 'あの方は せんせいです', options: ['Siswa', 'Guru', 'Kepala Sekolah', 'Teman'], answer: 1 },
        { question: 'Dengarkan letak benda ini:', audioText: 'つくえの うえに あります', options: ['Di bawah meja', 'Di dalam meja', 'Di atas meja', 'Di samping meja'], answer: 2 },
        { question: 'Pilih kata kerja yang disebutkan:', audioText: 'にほんごを べんきょうします', options: ['Bermain', 'Belajar', 'Bekerja', 'Beristirahat'], answer: 1 },
        { question: 'Dengarkan sapaan sebelum makan:', audioText: 'いただきます', options: ['Terima kasih', 'Selamat makan', 'Sampai jumpa', 'Enak sekali'], answer: 1 },
        { question: 'Apa yang sedang dilakukan?', audioText: 'てがみを かいています', options: ['Membaca surat', 'Menulis surat', 'Mengirim surat', 'Menerima surat'], answer: 1 }
    ]
};
